enum CompliancePortalVisibility
    @goModel(model: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibility") {
    NONE
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibilityNone"
        )
    RESTRICTED
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibilityRestricted"
        )
    PUBLIC
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibilityPublic"
        )
}

enum CompliancePortalLinkedVisibility
    @goModel(model: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibility") {
    RESTRICTED
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibilityRestricted"
        )
    PUBLIC
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalVisibilityPublic"
        )
}

enum SearchEngineIndexing
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.SearchEngineIndexing"
    ) {
    INDEXABLE
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.SearchEngineIndexingIndexable"
        )
    NOT_INDEXABLE
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.SearchEngineIndexingNotIndexable"
        )
}

enum CompliancePortalDocumentAccessStatus
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessStatus"
    ) {
    REQUESTED
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessStatusRequested"
        )
    GRANTED
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessStatusGranted"
        )
    REJECTED
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessStatusRejected"
        )
    REVOKED
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessStatusRevoked"
        )
}

enum CompliancePortalAccessOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalAccessOrderField"
    ) {
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalAccessOrderFieldCreatedAt"
        )
}

enum CompliancePortalAccessState
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalAccessState"
    ) {
    ACTIVE
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalAccessStateActive"
        )
    INACTIVE
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalAccessStateInactive"
        )
}

enum CompliancePortalDocumentAccessOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessOrderField"
    ) {
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalDocumentAccessOrderFieldCreatedAt"
        )
}

enum CompliancePortalReferenceOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalReferenceOrderField"
    ) {
    RANK
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalReferenceOrderFieldRank"
        )
    NAME
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalReferenceOrderFieldName"
        )
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalReferenceOrderFieldCreatedAt"
        )
    UPDATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalReferenceOrderFieldUpdatedAt"
        )
}

enum CompliancePortalCommitmentGroupOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentGroupOrderField"
    ) {
    RANK
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentGroupOrderFieldRank"
        )
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentGroupOrderFieldCreatedAt"
        )
    UPDATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentGroupOrderFieldUpdatedAt"
        )
}

enum CompliancePortalCommitmentOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentOrderField"
    ) {
    RANK
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentOrderFieldRank"
        )
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentOrderFieldCreatedAt"
        )
    UPDATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentOrderFieldUpdatedAt"
        )
}

enum CompliancePortalCommitmentIcon
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIcon"
    ) {
    LOCK_KEY
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconLockKey")
    EYE_SLASH
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconEyeSlash")
    FINGERPRINT
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconFingerprint")
    SHIELD_WARNING
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconShieldWarning")
    SHIELD_CHECK
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconShieldCheck")
    SIREN
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconSiren")
    KEY
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconKey")
    LOCK
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconLock")
    CLOUD
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconCloud")
    DATABASE
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconDatabase")
    GLOBE
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconGlobe")
    EYE
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconEye")
    USERS
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconUsers")
    CERTIFICATE
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconCertificate")
    GAVEL
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconGavel")
    HEARTBEAT
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconHeartbeat")
    BELL
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconBell")
    BUG
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconBug")
    CODE
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconCode")
    SERVER
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CompliancePortalCommitmentIconServer")
}

enum ComplianceCustomLinkOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.ComplianceCustomLinkOrderField"
    ) {
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.ComplianceCustomLinkOrderFieldCreatedAt"
        )
    RANK
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.ComplianceCustomLinkOrderFieldRank"
        )
}

enum ComplianceFrameworkOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.ComplianceFrameworkOrderField"
    ) {
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.ComplianceFrameworkOrderFieldCreatedAt"
        )
    RANK
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.ComplianceFrameworkOrderFieldRank"
        )
}

enum ComplianceFrameworkVisibility
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.ComplianceFrameworkVisibility"
    ) {
    NONE
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.ComplianceFrameworkVisibilityNone"
        )
    PUBLIC
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.ComplianceFrameworkVisibilityPublic"
        )
}

enum CompliancePortalFileOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalFileOrderField"
    ) {
    NAME
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalFileOrderFieldName"
        )
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalFileOrderFieldCreatedAt"
        )
    UPDATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalFileOrderFieldUpdatedAt"
        )
}

enum SSLStatus
    @goModel(model: "go.probo.inc/probo/pkg/coredata.CertificateStatus") {
    PENDING
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CertificateStatusPending")
    PROVISIONING
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CertificateStatusProvisioning"
        )
    ACTIVE
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CertificateStatusActive")
    RENEWING
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CertificateStatusRenewing")
    EXPIRED
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CertificateStatusExpired")
    FAILED
        @goEnum(value: "go.probo.inc/probo/pkg/coredata.CertificateStatusFailed")
}

input CompliancePortalAccessOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalAccessOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalAccessOrderField!
}

input CompliancePortalDocumentAccessOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalDocumentAccessOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalDocumentAccessOrderField!
}

input CompliancePortalReferenceOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalReferenceOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalReferenceOrderField!
}

input CompliancePortalCommitmentGroupOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalCommitmentGroupOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalCommitmentGroupOrderField!
}

input CompliancePortalCommitmentOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalCommitmentOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalCommitmentOrderField!
}

input CompliancePortalFileOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalFileOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalFileOrderField!
}

input ComplianceCustomLinkOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.ComplianceCustomLinkOrderBy"
    ) {
    direction: OrderDirection!
    field: ComplianceCustomLinkOrderField!
}

input ComplianceFrameworkOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.ComplianceFrameworkOrderBy"
    ) {
    direction: OrderDirection!
    field: ComplianceFrameworkOrderField!
}

enum CompliancePortalOrderField
    @goModel(
        model: "go.probo.inc/probo/pkg/coredata.CompliancePortalOrderField"
    ) {
    CREATED_AT
        @goEnum(
            value: "go.probo.inc/probo/pkg/coredata.CompliancePortalOrderFieldCreatedAt"
        )
}

input CompliancePortalOrder
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalOrderBy"
    ) {
    direction: OrderDirection!
    field: CompliancePortalOrderField!
}

type CompliancePortal implements Node
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortal"
    ) {
    id: ID!
    active: Boolean!
    searchEngineIndexing: SearchEngineIndexing!
    logo: File @goField(forceResolver: true)
    darkLogo: File @goField(forceResolver: true)
    nda: File @goField(forceResolver: true)
    description: String
    websiteUrl: String
    email: String
    headquarterAddress: String
    entityName: String!
    slug: String!
    createdAt: Datetime!
    updatedAt: Datetime!
    organization: Organization! @goField(forceResolver: true)

    accesses(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: CompliancePortalAccessOrder
    ): CompliancePortalAccessConnection! @goField(forceResolver: true)

    references(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: CompliancePortalReferenceOrder
    ): CompliancePortalReferenceConnection! @goField(forceResolver: true)

    commitmentGroups(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: CompliancePortalCommitmentGroupOrder
    ): CompliancePortalCommitmentGroupConnection! @goField(forceResolver: true)

    complianceFrameworks(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: ComplianceFrameworkOrder
    ): ComplianceFrameworkConnection! @goField(forceResolver: true)

    customLinks(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: ComplianceCustomLinkOrder
    ): ComplianceCustomLinkConnection! @goField(forceResolver: true)

    compliancePortalFiles(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: CompliancePortalFileOrder
    ): CompliancePortalFileConnection! @goField(forceResolver: true)

    documents(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: DocumentOrder
    ): CompliancePortalDocumentConnection! @goField(forceResolver: true)

    audits(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: AuditOrder
    ): CompliancePortalAuditConnection! @goField(forceResolver: true)

    thirdParties(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: ThirdPartyOrder
    ): CompliancePortalThirdPartyConnection! @goField(forceResolver: true)

    mailingList: MailingList @goField(forceResolver: true)

    defaultDomain: CustomDomain @goField(forceResolver: true)

    customDomain: CustomDomain @goField(forceResolver: true)

    publicUrl: String! @goField(forceResolver: true)

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type CompliancePortalConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalDocument
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalDocument"
    ) {
    id: ID!
    document: Document!
    visibility: CompliancePortalLinkedVisibility!
}

type CompliancePortalDocumentConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalDocumentConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalDocumentEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalDocumentEdge {
    cursor: CursorKey!
    node: CompliancePortalDocument!
}

type CompliancePortalAudit
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalAudit"
    ) {
    id: ID!
    audit: Audit!
    visibility: CompliancePortalLinkedVisibility!
}

type CompliancePortalAuditConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalAuditConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalAuditEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalAuditEdge {
    cursor: CursorKey!
    node: CompliancePortalAudit!
}

type CompliancePortalThirdParty
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalThirdParty"
    ) {
    id: ID!
    thirdParty: ThirdParty!
}

type CompliancePortalThirdPartyConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalThirdPartyConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalThirdPartyEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalThirdPartyEdge {
    cursor: CursorKey!
    node: CompliancePortalThirdParty!
}

type CompliancePortalEdge {
    cursor: CursorKey!
    node: CompliancePortal!
}

type CompliancePortalAccess implements Node {
    id: ID!
    ndaSignature: ElectronicSignature @goField(forceResolver: true)
    createdAt: Datetime!
    updatedAt: Datetime!
    pendingRequestCount: Int! @goField(forceResolver: true)
    activeCount: Int! @goField(forceResolver: true)
    organizationId: ID!
    identityID: ID!

    profile: Profile! @goField(forceResolver: true)

    availableDocumentAccesses(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: CompliancePortalDocumentAccessOrder
    ): CompliancePortalDocumentAccessConnection! @goField(forceResolver: true)

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type CompliancePortalDocumentAccess
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalDocumentAccess"
    ) {
    id: ID!
    status: CompliancePortalDocumentAccessStatus!
    document: Document @goField(forceResolver: true)
    reportFile: File @goField(forceResolver: true)
    audit: Audit @goField(forceResolver: true)
    compliancePortalFile: CompliancePortalFile @goField(forceResolver: true)
}

type CompliancePortalDocumentAccessConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalDocumentAccessConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalDocumentAccessEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalDocumentAccessEdge {
    cursor: CursorKey!
    node: CompliancePortalDocumentAccess!
}

type CompliancePortalAccessConnection {
    edges: [CompliancePortalAccessEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalAccessEdge {
    cursor: CursorKey!
    node: CompliancePortalAccess!
}

type CompliancePortalReference implements Node {
    id: ID!
    name: String!
    description: String
    websiteUrl: String!
    logo: File! @goField(forceResolver: true)
    rank: Int!
    createdAt: Datetime!
    updatedAt: Datetime!

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type CompliancePortalReferenceConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalReferenceConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalReferenceEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalReferenceEdge {
    cursor: CursorKey!
    node: CompliancePortalReference!
}

type CompliancePortalCommitmentGroup implements Node {
    id: ID!
    title: String!
    description: String!
    rank: Int!
    createdAt: Datetime!
    updatedAt: Datetime!

    commitments(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: CompliancePortalCommitmentOrder
    ): CompliancePortalCommitmentConnection! @goField(forceResolver: true)

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type CompliancePortalCommitmentGroupConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalCommitmentGroupConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalCommitmentGroupEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalCommitmentGroupEdge {
    cursor: CursorKey!
    node: CompliancePortalCommitmentGroup!
}

type CompliancePortalCommitment implements Node {
    id: ID!
    icon: CompliancePortalCommitmentIcon!
    eyebrow: String!
    title: String!
    description: String!
    rank: Int!
    createdAt: Datetime!
    updatedAt: Datetime!

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type CompliancePortalCommitmentConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalCommitmentConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalCommitmentEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalCommitmentEdge {
    cursor: CursorKey!
    node: CompliancePortalCommitment!
}

type ComplianceFramework implements Node
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.ComplianceFramework"
    ) {
    id: ID!
    framework: Framework! @goField(forceResolver: true)
    rank: Int!
    visibility: ComplianceFrameworkVisibility!
    createdAt: Datetime!
    updatedAt: Datetime!
}

type ComplianceFrameworkConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.ComplianceFrameworkConnection"
    ) {
    edges: [ComplianceFrameworkEdge!]!
    pageInfo: PageInfo!
}

type ComplianceFrameworkEdge {
    cursor: CursorKey!
    node: ComplianceFramework!
}

type ComplianceCustomLink implements Node {
    id: ID!
    name: String!
    url: String!
    rank: Int!
    createdAt: Datetime!
    updatedAt: Datetime!

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type ComplianceCustomLinkConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.ComplianceCustomLinkConnection"
    ) {
    edges: [ComplianceCustomLinkEdge!]!
    pageInfo: PageInfo!
}

type ComplianceCustomLinkEdge {
    cursor: CursorKey!
    node: ComplianceCustomLink!
}

type CompliancePortalFile implements Node {
    id: ID!
    name: String!
    category: String!
    file: File! @goField(forceResolver: true)
    compliancePortalVisibility: CompliancePortalVisibility!
    alias: String @goField(forceResolver: true)
    createdAt: Datetime!
    updatedAt: Datetime!
    organization: Organization! @goField(forceResolver: true)

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type CompliancePortalFileConnection
    @goModel(
        model: "go.probo.inc/probo/pkg/server/api/console/v1/types.CompliancePortalFileConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [CompliancePortalFileEdge!]!
    pageInfo: PageInfo!
}

type CompliancePortalFileEdge {
    cursor: CursorKey!
    node: CompliancePortalFile!
}

type CustomDomain implements Node {
    id: ID!
    organization: Organization!
    domain: String!
    managed: Boolean!
    certificate: Certificate @goField(forceResolver: true)
    dnsRecords: [DNSRecordInstruction!]!
    createdAt: Datetime!
    updatedAt: Datetime!

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type Certificate {
    id: ID!
    status: SSLStatus!
    expiresAt: Datetime
    provisioningError: String
}

type DNSRecordInstruction {
    type: String!
    name: String!
    value: String!
    ttl: Int!
    purpose: String!
}

extend type Mutation {
    createCompliancePortal(
        input: CreateCompliancePortalInput!
    ): CreateCompliancePortalPayload!
    deleteCompliancePortal(
        input: DeleteCompliancePortalInput!
    ): DeleteCompliancePortalPayload!
    updateCompliancePortalDocumentVisibility(
        input: UpdateCompliancePortalDocumentVisibilityInput!
    ): UpdateCompliancePortalDocumentVisibilityPayload!
    deleteCompliancePortalDocument(
        input: DeleteCompliancePortalDocumentInput!
    ): DeleteCompliancePortalDocumentPayload!
    updateCompliancePortalAuditVisibility(
        input: UpdateCompliancePortalAuditVisibilityInput!
    ): UpdateCompliancePortalAuditVisibilityPayload!
    deleteCompliancePortalAudit(
        input: DeleteCompliancePortalAuditInput!
    ): DeleteCompliancePortalAuditPayload!
    updateCompliancePortalThirdPartyPublished(
        input: UpdateCompliancePortalThirdPartyPublishedInput!
    ): UpdateCompliancePortalThirdPartyPublishedPayload!
    deleteCompliancePortalThirdParty(
        input: DeleteCompliancePortalThirdPartyInput!
    ): DeleteCompliancePortalThirdPartyPayload!
    updateCompliancePortal(input: UpdateCompliancePortalInput!): UpdateCompliancePortalPayload!
    uploadCompliancePortalNDA(
        input: UploadCompliancePortalNDAInput!
    ): UploadCompliancePortalNDAPayload!
    deleteCompliancePortalNDA(
        input: DeleteCompliancePortalNDAInput!
    ): DeleteCompliancePortalNDAPayload!
    updateCompliancePortalBrand(
        input: UpdateCompliancePortalBrandInput!
    ): UpdateCompliancePortalBrandPayload!
    updateCompliancePortalAccess(
        input: UpdateCompliancePortalAccessInput!
    ): UpdateCompliancePortalAccessPayload!
    deleteCompliancePortalAccess(
        input: DeleteCompliancePortalAccessInput!
    ): DeleteCompliancePortalAccessPayload!
    createCompliancePortalReference(
        input: CreateCompliancePortalReferenceInput!
    ): CreateCompliancePortalReferencePayload!
    updateCompliancePortalReference(
        input: UpdateCompliancePortalReferenceInput!
    ): UpdateCompliancePortalReferencePayload!
    deleteCompliancePortalReference(
        input: DeleteCompliancePortalReferenceInput!
    ): DeleteCompliancePortalReferencePayload!
    createCompliancePortalCommitmentGroup(
        input: CreateCompliancePortalCommitmentGroupInput!
    ): CreateCompliancePortalCommitmentGroupPayload!
    updateCompliancePortalCommitmentGroup(
        input: UpdateCompliancePortalCommitmentGroupInput!
    ): UpdateCompliancePortalCommitmentGroupPayload!
    deleteCompliancePortalCommitmentGroup(
        input: DeleteCompliancePortalCommitmentGroupInput!
    ): DeleteCompliancePortalCommitmentGroupPayload!
    createCompliancePortalCommitment(
        input: CreateCompliancePortalCommitmentInput!
    ): CreateCompliancePortalCommitmentPayload!
    updateCompliancePortalCommitment(
        input: UpdateCompliancePortalCommitmentInput!
    ): UpdateCompliancePortalCommitmentPayload!
    deleteCompliancePortalCommitment(
        input: DeleteCompliancePortalCommitmentInput!
    ): DeleteCompliancePortalCommitmentPayload!
    createComplianceFramework(
        input: CreateComplianceFrameworkInput!
    ): CreateComplianceFrameworkPayload!
    updateComplianceFramework(
        input: UpdateComplianceFrameworkInput!
    ): UpdateComplianceFrameworkPayload!
    deleteComplianceFramework(
        input: DeleteComplianceFrameworkInput!
    ): DeleteComplianceFrameworkPayload!
    createComplianceCustomLink(
        input: CreateComplianceCustomLinkInput!
    ): CreateComplianceCustomLinkPayload!
    updateComplianceCustomLink(
        input: UpdateComplianceCustomLinkInput!
    ): UpdateComplianceCustomLinkPayload!
    deleteComplianceCustomLink(
        input: DeleteComplianceCustomLinkInput!
    ): DeleteComplianceCustomLinkPayload!
    createCompliancePortalFile(
        input: CreateCompliancePortalFileInput!
    ): CreateCompliancePortalFilePayload!
    updateCompliancePortalFile(
        input: UpdateCompliancePortalFileInput!
    ): UpdateCompliancePortalFilePayload!
    getCompliancePortalFile(
        input: GetCompliancePortalFileInput!
    ): GetCompliancePortalFilePayload!
    deleteCompliancePortalFile(
        input: DeleteCompliancePortalFileInput!
    ): DeleteCompliancePortalFilePayload!
    createCustomDomain(
        input: CreateCustomDomainInput!
    ): CreateCustomDomainPayload!
    deleteCustomDomain(
        input: DeleteCustomDomainInput!
    ): DeleteCustomDomainPayload!
}

input CreateCompliancePortalInput {
    organizationId: ID!
    entityName: String!
}

input DeleteCompliancePortalInput {
    compliancePortalId: ID!
}

input UpdateCompliancePortalInput {
    compliancePortalId: ID!
    active: Boolean
    searchEngineIndexing: SearchEngineIndexing
    entityName: String
    description: String @goField(omittable: true)
    websiteUrl: String @goField(omittable: true)
    email: String @goField(omittable: true)
    headquarterAddress: String @goField(omittable: true)
}

input UploadCompliancePortalNDAInput {
    compliancePortalId: ID!
    fileName: String!
    file: Upload!
}

input DeleteCompliancePortalNDAInput {
    compliancePortalId: ID!
}

input UpdateCompliancePortalBrandInput {
    compliancePortalId: ID!
    logoFile: Upload @goField(omittable: true)
    darkLogoFile: Upload @goField(omittable: true)
}

input CompliancePortalDocumentAccessInput {
    id: ID!
    status: CompliancePortalDocumentAccessStatus!
}

input UpdateCompliancePortalAccessInput {
    id: ID!
    name: String
    state: CompliancePortalAccessState
    documents: [CompliancePortalDocumentAccessInput!]
    reports: [CompliancePortalDocumentAccessInput!]
    compliancePortalFiles: [CompliancePortalDocumentAccessInput!]
}

input DeleteCompliancePortalAccessInput {
    id: ID!
}

input CreateCompliancePortalReferenceInput {
    compliancePortalId: ID!
    name: String!
    description: String
    websiteUrl: String!
    logoFile: Upload!
}

input UpdateCompliancePortalReferenceInput {
    id: ID!
    name: String
    description: String @goField(omittable: true)
    websiteUrl: String
    logoFile: Upload
    rank: Int
}

input DeleteCompliancePortalReferenceInput {
    id: ID!
}

input CreateCompliancePortalCommitmentGroupInput {
    compliancePortalId: ID!
    title: String!
    description: String!
}

input UpdateCompliancePortalCommitmentGroupInput {
    id: ID!
    title: String
    description: String
    rank: Int
}

input DeleteCompliancePortalCommitmentGroupInput {
    id: ID!
}

input CreateCompliancePortalCommitmentInput {
    groupId: ID!
    icon: CompliancePortalCommitmentIcon!
    eyebrow: String!
    title: String!
    description: String!
}

input UpdateCompliancePortalCommitmentInput {
    id: ID!
    icon: CompliancePortalCommitmentIcon
    eyebrow: String
    title: String
    description: String
    rank: Int
}

input DeleteCompliancePortalCommitmentInput {
    id: ID!
}

input CreateComplianceFrameworkInput {
    compliancePortalId: ID!
    frameworkId: ID!
}

input UpdateComplianceFrameworkInput {
    id: ID!
    rank: Int!
}

input DeleteComplianceFrameworkInput {
    id: ID!
}

input CreateComplianceCustomLinkInput {
    compliancePortalId: ID!
    name: String!
    url: String!
}

input UpdateComplianceCustomLinkInput {
    id: ID!
    name: String!
    url: String!
    rank: Int
}

input DeleteComplianceCustomLinkInput {
    id: ID!
}

input CreateCompliancePortalFileInput {
    compliancePortalId: ID!
    name: String!
    category: String!
    file: Upload!
    compliancePortalVisibility: CompliancePortalVisibility!
}

input UpdateCompliancePortalDocumentVisibilityInput {
    compliancePortalId: ID!
    documentId: ID!
    compliancePortalVisibility: CompliancePortalLinkedVisibility!
}

input DeleteCompliancePortalDocumentInput {
    id: ID!
}

input UpdateCompliancePortalAuditVisibilityInput {
    compliancePortalId: ID!
    auditId: ID!
    compliancePortalVisibility: CompliancePortalLinkedVisibility!
}

input DeleteCompliancePortalAuditInput {
    id: ID!
}

input UpdateCompliancePortalThirdPartyPublishedInput {
    compliancePortalId: ID!
    thirdPartyId: ID!
    published: Boolean!
}

input DeleteCompliancePortalThirdPartyInput {
    id: ID!
}

type UpdateCompliancePortalDocumentVisibilityPayload {
    catalogDocument: CompliancePortalDocument!
    catalogDocumentEdge: CompliancePortalDocumentEdge!
}

type DeleteCompliancePortalDocumentPayload {
    deletedCompliancePortalDocumentId: ID!
}

type UpdateCompliancePortalAuditVisibilityPayload {
    catalogAudit: CompliancePortalAudit!
    catalogAuditEdge: CompliancePortalAuditEdge!
}

type DeleteCompliancePortalAuditPayload {
    deletedCompliancePortalAuditId: ID!
}

type UpdateCompliancePortalThirdPartyPublishedPayload {
    catalogThirdParty: CompliancePortalThirdParty!
    catalogThirdPartyEdge: CompliancePortalThirdPartyEdge!
}

type DeleteCompliancePortalThirdPartyPayload {
    deletedCompliancePortalThirdPartyId: ID!
}

input UpdateCompliancePortalFileInput {
    id: ID!
    name: String
    category: String
    compliancePortalVisibility: CompliancePortalVisibility
}

input GetCompliancePortalFileInput {
    id: ID!
}

input DeleteCompliancePortalFileInput {
    id: ID!
}

input CreateCustomDomainInput {
    compliancePortalId: ID!
    domain: String!
}

input DeleteCustomDomainInput {
    customDomainId: ID!
}

type CreateCompliancePortalPayload {
    compliancePortalEdge: CompliancePortalEdge!
}

type DeleteCompliancePortalPayload {
    deletedCompliancePortalId: ID!
}

type UpdateCompliancePortalPayload {
    compliancePortal: CompliancePortal!
}

type UploadCompliancePortalNDAPayload {
    compliancePortal: CompliancePortal!
}

type DeleteCompliancePortalNDAPayload {
    compliancePortal: CompliancePortal!
}

type UpdateCompliancePortalBrandPayload {
    compliancePortal: CompliancePortal!
}

type UpdateCompliancePortalAccessPayload {
    compliancePortalAccess: CompliancePortalAccess!
}

type DeleteCompliancePortalAccessPayload {
    deletedCompliancePortalAccessId: ID!
}

type CreateCompliancePortalReferencePayload {
    compliancePortalReferenceEdge: CompliancePortalReferenceEdge!
}

type UpdateCompliancePortalReferencePayload {
    compliancePortalReference: CompliancePortalReference!
}

type DeleteCompliancePortalReferencePayload {
    deletedCompliancePortalReferenceId: ID!
}

type CreateCompliancePortalCommitmentGroupPayload {
    compliancePortalCommitmentGroupEdge: CompliancePortalCommitmentGroupEdge!
}

type UpdateCompliancePortalCommitmentGroupPayload {
    compliancePortalCommitmentGroup: CompliancePortalCommitmentGroup!
}

type DeleteCompliancePortalCommitmentGroupPayload {
    deletedCompliancePortalCommitmentGroupId: ID!
}

type CreateCompliancePortalCommitmentPayload {
    compliancePortalCommitmentEdge: CompliancePortalCommitmentEdge!
}

type UpdateCompliancePortalCommitmentPayload {
    compliancePortalCommitment: CompliancePortalCommitment!
}

type DeleteCompliancePortalCommitmentPayload {
    deletedCompliancePortalCommitmentId: ID!
}

type CreateComplianceFrameworkPayload {
    complianceFrameworkEdge: ComplianceFrameworkEdge!
}

type UpdateComplianceFrameworkPayload {
    complianceFramework: ComplianceFramework!
}

type DeleteComplianceFrameworkPayload {
    deletedComplianceFrameworkId: ID!
}

type CreateComplianceCustomLinkPayload {
    complianceCustomLinkEdge: ComplianceCustomLinkEdge!
}

type UpdateComplianceCustomLinkPayload {
    complianceCustomLink: ComplianceCustomLink!
}

type DeleteComplianceCustomLinkPayload {
    deletedComplianceCustomLinkId: ID!
}

type CreateCompliancePortalFilePayload {
    compliancePortalFileEdge: CompliancePortalFileEdge!
}

type UpdateCompliancePortalFilePayload {
    compliancePortalFile: CompliancePortalFile!
}

type GetCompliancePortalFilePayload {
    compliancePortalFile: CompliancePortalFile!
}

type DeleteCompliancePortalFilePayload {
    deletedCompliancePortalFileId: ID!
}

type CreateCustomDomainPayload {
    customDomain: CustomDomain!
}

type DeleteCustomDomainPayload {
    deletedCustomDomainId: ID!
}
