package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// Organization is the resolver for the organization field.
func (r *auditProgramResolver) Organization(ctx context.Context, obj *types.AuditProgram) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot load organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Framework is the resolver for the framework field.
func (r *auditProgramResolver) Framework(ctx context.Context, obj *types.AuditProgram) (*types.Framework, error) {
	if _, err := r.authorize(ctx, obj.Framework.ID, probo.ActionFrameworkGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	framework, err := loaders.Framework.Load(ctx, obj.Framework.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot load framework", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewFramework(framework), nil
}

// Audits is the resolver for the audits field.
func (r *auditProgramResolver) Audits(ctx context.Context, obj *types.AuditProgram, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.AuditOrderBy) (*types.AuditConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionAuditList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.AuditOrderField]{
		Field:     coredata.AuditOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.AuditOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.probo.Audits.ListForAuditProgramID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list audit program audits", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewAuditConnection(p, r, obj.ID), nil
}

// Permission is the resolver for the permission field.
func (r *auditProgramResolver) Permission(ctx context.Context, obj *types.AuditProgram, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *auditProgramConnectionResolver) TotalCount(ctx context.Context, obj *types.AuditProgramConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionAuditProgramList)
	if err != nil {
		return 0, err
	}

	switch obj.Resolver.(type) {
	case *organizationResolver:
		count, err := r.probo.AuditPrograms.CountForOrganizationID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count audit programs", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	default:
		r.logger.ErrorCtx(ctx, "unsupported resolver", log.Any("resolver", obj.Resolver))
		return 0, gqlutils.Internal(ctx)
	}
}

// CreateAuditProgram is the resolver for the createAuditProgram field.
func (r *mutationResolver) CreateAuditProgram(ctx context.Context, input types.CreateAuditProgramInput) (*types.CreateAuditProgramPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionAuditProgramCreate)
	if err != nil {
		return nil, err
	}

	req := probo.CreateAuditProgramRequest{
		OrganizationID: input.OrganizationID,
		FrameworkID:    input.FrameworkID,
		Name:           input.Name,
		ValidFrom:      input.ValidFrom,
		ValidUntil:     input.ValidUntil,
	}

	auditProgram, err := r.probo.AuditPrograms.Create(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot create audit program", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateAuditProgramPayload{
		AuditProgramEdge: types.NewAuditProgramEdge(auditProgram, coredata.AuditProgramOrderFieldCreatedAt),
	}, nil
}

// UpdateAuditProgram is the resolver for the updateAuditProgram field.
func (r *mutationResolver) UpdateAuditProgram(ctx context.Context, input types.UpdateAuditProgramInput) (*types.UpdateAuditProgramPayload, error) {
	scope, err := r.authorize(ctx, input.ID, probo.ActionAuditProgramUpdate)
	if err != nil {
		return nil, err
	}

	req := probo.UpdateAuditProgramRequest{
		ID:         input.ID,
		Name:       input.Name,
		ValidFrom:  gqlutils.UnwrapOmittable(input.ValidFrom),
		ValidUntil: gqlutils.UnwrapOmittable(input.ValidUntil),
	}

	auditProgram, err := r.probo.AuditPrograms.Update(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot update audit program", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateAuditProgramPayload{
		AuditProgram: types.NewAuditProgram(auditProgram),
	}, nil
}

// DeleteAuditProgram is the resolver for the deleteAuditProgram field.
func (r *mutationResolver) DeleteAuditProgram(ctx context.Context, input types.DeleteAuditProgramInput) (*types.DeleteAuditProgramPayload, error) {
	scope, err := r.authorize(ctx, input.AuditProgramID, probo.ActionAuditProgramDelete)
	if err != nil {
		return nil, err
	}

	if err := r.probo.AuditPrograms.Delete(ctx, scope, input.AuditProgramID); err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete audit program", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteAuditProgramPayload{
		DeletedAuditProgramID: &input.AuditProgramID,
	}, nil
}

// AuditProgram returns schema.AuditProgramResolver implementation.
func (r *Resolver) AuditProgram() schema.AuditProgramResolver { return &auditProgramResolver{r} }

// AuditProgramConnection returns schema.AuditProgramConnectionResolver implementation.
func (r *Resolver) AuditProgramConnection() schema.AuditProgramConnectionResolver {
	return &auditProgramConnectionResolver{r}
}

type (
	auditProgramResolver           struct{ *Resolver }
	auditProgramConnectionResolver struct{ *Resolver }
)
