package complianceportal_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/complianceportal/visitor"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/complianceportal"
	"go.probo.inc/probo/pkg/server/api/complianceportal/v1/schema"
	"go.probo.inc/probo/pkg/server/api/complianceportal/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// Framework is the resolver for the framework field.
func (r *auditResolver) Framework(ctx context.Context, obj *types.Audit) (*types.Framework, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	audit, err := visitorService.GetAuditForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrAuditNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "audit %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load audit", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	framework, err := visitorService.GetFrameworkForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		audit.FrameworkID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrFrameworkNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "framework %q not found", audit.FrameworkID)
		}

		r.logger.ErrorCtx(ctx, "cannot load framework", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewFramework(framework), nil
}

// ReportFile is the resolver for the reportFile field.
func (r *auditResolver) ReportFile(ctx context.Context, obj *types.Audit) (*types.AuditReport, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	audit, err := visitorService.GetAuditForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrAuditNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot load audit", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if audit.ReportFileID == nil {
		return nil, nil
	}

	file, err := visitorService.GetReport(ctx, scope, compliancePortal.ID, *audit.ReportFileID)
	if err != nil {
		if errors.Is(err, visitor.ErrReportNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot load report file", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewAuditReport(file), nil
}

// Alias is the resolver for the alias field.
func (r *auditReportResolver) Alias(ctx context.Context, obj *types.AuditReport) (*string, error) {
	return r.ResourceAliasResolver(ctx, obj.ID)
}

// IsUserAuthorized is the resolver for the isUserAuthorized field.
func (r *auditReportResolver) IsUserAuthorized(ctx context.Context, obj *types.AuditReport) (bool, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	_, portalAudit, err := visitorService.GetAuditByReportFileID(ctx, scope, compliancePortal.ID, obj.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, visitor.ErrReportNotFound) {
			return false, nil
		}

		r.logger.ErrorCtx(ctx, "cannot load audit for report file", log.Error(err))

		return false, gqlutils.Internal(ctx)
	}

	if portalAudit.Visibility == coredata.CompliancePortalVisibilityPublic {
		return true, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return false, nil
	}

	reportAccess, err := visitorService.GetPortalReportFileAccess(ctx, scope,
		compliancePortal.ID,
		identity.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrMembershipNotFound) ||
			errors.Is(err, visitor.ErrUserNotFound) ||
			errors.Is(err, visitor.ErrUserInactive) ||
			errors.Is(err, visitor.ErrDocumentAccessNotFound) {
			return false, nil
		}

		r.logger.ErrorCtx(ctx, "cannot check report access", log.Error(err))

		return false, gqlutils.Internal(ctx)
	}

	return reportAccess.Status == coredata.CompliancePortalDocumentAccessStatusGranted, nil
}

// Access is the resolver for the access field.
func (r *auditReportResolver) Access(ctx context.Context, obj *types.AuditReport) (*types.DocumentAccess, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, nil
	}

	access, err := visitorService.GetPortalReportFileAccess(
		ctx, scope,
		compliancePortal.ID,
		identity.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrMembershipNotFound) ||
			errors.Is(err, visitor.ErrUserNotFound) ||
			errors.Is(err, visitor.ErrDocumentAccessNotFound) {
			return nil, nil
		}

		if errors.Is(err, visitor.ErrUserInactive) {
			return nil, gqlutils.Forbidden(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get audit report access", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DocumentAccess{
		ID:     access.ID,
		Status: access.Status,
	}, nil
}

// Framework is the resolver for the framework field on ComplianceFramework.
func (r *complianceFrameworkResolver) Framework(ctx context.Context, obj *types.ComplianceFramework) (*types.Framework, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	complianceFramework, err := visitorService.GetComplianceFrameworkForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrFrameworkNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "compliance framework %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load compliance framework", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	framework, err := visitorService.GetFrameworkForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		complianceFramework.FrameworkID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrFrameworkNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "framework %q not found", complianceFramework.FrameworkID)
		}

		r.logger.ErrorCtx(ctx, "cannot load framework", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewFramework(framework), nil
}

// Logo is the resolver for the logo field.
func (r *compliancePortalResolver) Logo(ctx context.Context, obj *types.CompliancePortal) (*types.File, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	if compliancePortal.LogoFileID == nil {
		return nil, nil
	}

	return r.loadPublicFile(ctx, *compliancePortal.LogoFileID)
}

// DarkLogo is the resolver for the darkLogo field.
func (r *compliancePortalResolver) DarkLogo(ctx context.Context, obj *types.CompliancePortal) (*types.File, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	if compliancePortal.DarkLogoFileID == nil {
		return nil, nil
	}

	return r.loadPublicFile(ctx, *compliancePortal.DarkLogoFileID)
}

// NonDisclosureAgreement is the resolver for the nonDisclosureAgreement field.
func (r *compliancePortalResolver) NonDisclosureAgreement(ctx context.Context, obj *types.CompliancePortal) (*types.NonDisclosureAgreement, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	if compliancePortal.NonDisclosureAgreementFileID == nil {
		return nil, nil
	}

	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor

	file, err := visitorService.GetPortalNDAFile(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load NDA file", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	if file == nil {
		return nil, nil
	}

	return types.NewNonDisclosureAgreement(file), nil
}

// ViewerSubscription is the resolver for the viewerSubscription field.
func (r *compliancePortalResolver) ViewerSubscription(ctx context.Context, obj *types.CompliancePortal) (*types.MailingListSubscriber, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	if compliancePortal.MailingListID == nil {
		return nil, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, nil
	}

	subscriber, err := r.mailman.GetSubscriber(ctx, *compliancePortal.MailingListID, identity.EmailAddress)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot get mailing list subscription", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	if subscriber == nil {
		return nil, nil
	}

	return types.NewMailingListSubscriber(subscriber), nil
}

// Documents is the resolver for the documents field.
func (r *compliancePortalResolver) Documents(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey, filter *types.CompliancePortalVisibilityFilter) (*types.DocumentConnection, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.DocumentOrderField]{
		Field:     coredata.DocumentOrderFieldTitle,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	documentFilter := coredata.NewDocumentCompliancePortalFilter()
	if filter != nil && filter.Visibility != nil {
		documentFilter = documentFilter.WithCompliancePortalVisibilities(*filter.Visibility)
	}

	documentPage, err := visitorService.ListDocumentsForCompliancePortalID(ctx, scope, compliancePortal.ID, cursor, documentFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list public documents", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewDocumentConnection(documentPage), nil
}

// Audits is the resolver for the audits field.
func (r *compliancePortalResolver) Audits(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey, filter *types.CompliancePortalVisibilityFilter) (*types.AuditConnection, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.AuditOrderField]{
		Field:     coredata.AuditOrderFieldValidFrom,
		Direction: page.OrderDirectionDesc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	auditFilter := coredata.NewAuditCompliancePortalFilter()
	if filter != nil && filter.Visibility != nil {
		auditFilter = auditFilter.WithCompliancePortalVisibilities(*filter.Visibility)
	}

	auditPage, err := visitorService.ListAuditsForCompliancePortalID(ctx, scope, compliancePortal.ID, cursor, auditFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list public audits", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewAuditConnection(auditPage), nil
}

// Subprocessors is the resolver for the subprocessors field.
func (r *compliancePortalResolver) Subprocessors(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey, filter *types.SubprocessorFilter) (*types.SubprocessorConnection, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.ThirdPartyOrderField]{
		Field:     coredata.ThirdPartyOrderFieldName,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	var (
		query    *string
		category *coredata.ThirdPartyCategory
		country  *coredata.CountryCode
	)
	if filter != nil {
		query = filter.Query
		category = filter.Category
		country = filter.Country
	}

	if category != nil && !category.IsValid() {
		return nil, gqlutils.Invalidf(ctx, "invalid subprocessor category filter: %q", string(*category))
	}

	if country != nil && !country.IsValid() {
		return nil, gqlutils.Invalidf(ctx, "invalid subprocessor country filter: %q", string(*country))
	}

	thirdPartyFilter := coredata.NewThirdPartyFilter(nil, query, category, country)

	thirdPartyPage, err := visitorService.ListThirdPartiesForCompliancePortalID(ctx, scope, compliancePortal.ID, cursor, thirdPartyFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list subprocessors", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewSubprocessorConnection(thirdPartyPage, r, obj.ID, thirdPartyFilter), nil
}

// SubprocessorCategories is the resolver for the subprocessorCategories field.
func (r *compliancePortalResolver) SubprocessorCategories(ctx context.Context, obj *types.CompliancePortal) ([]coredata.ThirdPartyCategory, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)

	categories, err := r.visitor.ListDistinctPortalCategoriesForPortalID(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list subprocessor categories", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return categories, nil
}

// SubprocessorCountries is the resolver for the subprocessorCountries field.
func (r *compliancePortalResolver) SubprocessorCountries(ctx context.Context, obj *types.CompliancePortal) ([]coredata.CountryCode, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)

	countries, err := r.visitor.ListDistinctPortalCountriesForPortalID(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list subprocessor countries", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return countries, nil
}

// References is the resolver for the references field.
func (r *compliancePortalResolver) References(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.CompliancePortalReferenceConnection, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.CompliancePortalReferenceOrderField]{
		Field:     coredata.CompliancePortalReferenceOrderFieldRank,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	referencePage, err := visitorService.ListPortalReferencesForPortalID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list public compliance portal references", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewCompliancePortalReferenceConnection(referencePage), nil
}

// CommitmentGroups is the resolver for the commitmentGroups field.
func (r *compliancePortalResolver) CommitmentGroups(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.CompliancePortalCommitmentGroupConnection, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.CompliancePortalCommitmentGroupOrderField]{
		Field:     coredata.CompliancePortalCommitmentGroupOrderFieldRank,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	groupPage, err := visitorService.ListCommitmentGroupsForPortalID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list public compliance portal commitment groups", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewCompliancePortalCommitmentGroupConnection(groupPage), nil
}

// CompliancePortalFiles is the resolver for the compliancePortalFiles field.
func (r *compliancePortalResolver) CompliancePortalFiles(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey, filter *types.CompliancePortalVisibilityFilter) (*types.CompliancePortalFileConnection, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.CompliancePortalFileOrderField]{
		Field:     coredata.CompliancePortalFileOrderFieldName,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	visibilities := []coredata.CompliancePortalVisibility{
		coredata.CompliancePortalVisibilityPublic,
		coredata.CompliancePortalVisibilityRestricted,
	}
	if filter != nil && filter.Visibility != nil {
		visibilities = []coredata.CompliancePortalVisibility{*filter.Visibility}
	}

	fileFilter := coredata.NewCompliancePortalFileFilter(
		coredata.WithCompliancePortalFileVisibilities(visibilities...),
	)

	portalFilePage, err := visitorService.ListPortalFilesForCompliancePortalID(ctx, scope, compliancePortal.ID, cursor, fileFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list public compliance portal files", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewCompliancePortalFileConnection(portalFilePage), nil
}

// ComplianceFrameworks is the resolver for the complianceFrameworks field.
func (r *compliancePortalResolver) ComplianceFrameworks(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.ComplianceFrameworkConnection, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.ComplianceFrameworkOrderField]{
		Field:     coredata.ComplianceFrameworkOrderFieldRank,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	cfPage, err := visitorService.ListComplianceFrameworksByPortalID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list compliance frameworks", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewComplianceFrameworkConnection(cfPage), nil
}

// CustomLinks is the resolver for the customLinks field.
func (r *compliancePortalResolver) CustomLinks(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.ComplianceCustomLinkConnection, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor
	pageOrderBy := page.OrderBy[coredata.ComplianceCustomLinkOrderField]{
		Field:     coredata.ComplianceCustomLinkOrderFieldRank,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	result, err := visitorService.ListCustomLinksForPortalID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list compliance custom links", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewComplianceCustomLinkConnection(result), nil
}

// Updates is the resolver for the updates field.
func (r *compliancePortalResolver) Updates(ctx context.Context, obj *types.CompliancePortal, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.MailingListUpdateConnection, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)
	visitorService := r.visitor

	tc, err := visitorService.GetPortal(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load compliance portal", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	if tc.MailingListID == nil {
		return &types.MailingListUpdateConnection{Edges: []*types.MailingListUpdateEdge{}, PageInfo: &types.PageInfo{}}, nil
	}

	pageOrderBy := page.OrderBy[coredata.MailingListUpdateOrderField]{
		Field:     coredata.MailingListUpdateOrderFieldUpdatedAt,
		Direction: page.OrderDirectionDesc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	result, err := r.mailman.ListSentMailingListUpdates(ctx, *tc.MailingListID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list mailing list updates", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewMailingListUpdateConnection(result), nil
}

// Commitments is the resolver for the commitments field.
func (r *compliancePortalCommitmentGroupResolver) Commitments(ctx context.Context, obj *types.CompliancePortalCommitmentGroup, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.CompliancePortalCommitmentConnection, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)
	pageOrderBy := page.OrderBy[coredata.CompliancePortalCommitmentOrderField]{
		Field:     coredata.CompliancePortalCommitmentOrderFieldRank,
		Direction: page.OrderDirectionAsc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	commitmentPage, err := visitorService.ListCommitmentsForCompliancePortalGroupID(
		ctx,
		scope,
		compliancePortal.ID,
		obj.ID,
		cursor,
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "commitment group %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot list public compliance portal commitments", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewCompliancePortalCommitmentConnection(commitmentPage), nil
}

// Alias is the resolver for the alias field.
func (r *compliancePortalFileResolver) Alias(ctx context.Context, obj *types.CompliancePortalFile) (*string, error) {
	return r.ResourceAliasResolver(ctx, obj.ID)
}

// IsUserAuthorized is the resolver for the isUserAuthorized field.
func (r *compliancePortalFileResolver) IsUserAuthorized(ctx context.Context, obj *types.CompliancePortalFile) (bool, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	portalFile, err := visitorService.GetPortalFile(ctx, scope, compliancePortal.ID, obj.ID)
	if err != nil {
		if errors.Is(err, visitor.ErrPortalFileNotFound) || errors.Is(err, visitor.ErrPortalFileNotVisible) {
			return false, gqlutils.NotFoundf(ctx, "compliance portal file %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load compliance portal file", log.Error(err))

		return false, gqlutils.Internal(ctx)
	}

	if portalFile.CompliancePortalVisibility == coredata.CompliancePortalVisibilityPublic {
		return true, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return false, nil
	}

	fileAccess, err := visitorService.GetPortalFileAccess(ctx, scope,
		compliancePortal.ID,
		identity.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrMembershipNotFound) ||
			errors.Is(err, visitor.ErrUserNotFound) ||
			errors.Is(err, visitor.ErrUserInactive) ||
			errors.Is(err, visitor.ErrDocumentAccessNotFound) {
			return false, nil
		}

		r.logger.ErrorCtx(ctx, "cannot check compliance portal file access", log.Error(err))

		return false, gqlutils.Internal(ctx)
	}

	return fileAccess.Status == coredata.CompliancePortalDocumentAccessStatusGranted, nil
}

// Access is the resolver for the access field.
func (r *compliancePortalFileResolver) Access(ctx context.Context, obj *types.CompliancePortalFile) (*types.DocumentAccess, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, nil // User is not authenticated, so no access requested
	}

	access, err := visitorService.GetPortalFileAccess(
		ctx, scope,
		compliancePortal.ID,
		identity.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrMembershipNotFound) ||
			errors.Is(err, visitor.ErrUserNotFound) ||
			errors.Is(err, visitor.ErrDocumentAccessNotFound) {
			return nil, nil
		}

		if errors.Is(err, visitor.ErrUserInactive) {
			return nil, gqlutils.Forbidden(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get file access", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DocumentAccess{
		ID:     access.ID,
		Status: access.Status,
	}, nil
}

// Logo is the resolver for the logo field.
func (r *compliancePortalReferenceResolver) Logo(ctx context.Context, obj *types.CompliancePortalReference) (*types.File, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	reference, err := r.visitor.GetPortalReferenceForCompliancePortalID(ctx, scope, compliancePortal.ID, obj.ID)
	if err != nil {
		if errors.Is(err, visitor.ErrPortalReferenceNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "compliance portal reference %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load compliance portal reference", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return r.loadPublicFile(ctx, reference.LogoFileID)
}

// Alias is the resolver for the alias field.
func (r *documentResolver) Alias(ctx context.Context, obj *types.Document) (*string, error) {
	return r.ResourceAliasResolver(ctx, obj.ID)
}

// IsUserAuthorized is the resolver for the isUserAuthorized field.
func (r *documentResolver) IsUserAuthorized(ctx context.Context, obj *types.Document) (bool, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	_, portalDocument, err := visitorService.GetDocument(ctx, scope, compliancePortal.ID, obj.ID)
	if err != nil {
		if errors.Is(err, visitor.ErrDocumentNotFound) || errors.Is(err, visitor.ErrDocumentNotVisible) || errors.Is(err, coredata.ErrResourceNotFound) {
			return false, gqlutils.NotFoundf(ctx, "document %q not found", obj.ID)
		}

		if _, ok := errors.AsType[*visitor.ErrDocumentArchived](err); ok {
			return false, gqlutils.NotFoundf(ctx, "document %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load document", log.Error(err))

		return false, gqlutils.Internal(ctx)
	}

	if portalDocument.Visibility == coredata.CompliancePortalVisibilityPublic {
		return true, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return false, nil
	}

	documentAccess, err := visitorService.GetPortalDocumentAccess(
		ctx, scope,
		compliancePortal.ID,
		identity.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrMembershipNotFound) ||
			errors.Is(err, visitor.ErrUserNotFound) ||
			errors.Is(err, visitor.ErrUserInactive) ||
			errors.Is(err, visitor.ErrDocumentAccessNotFound) {
			return false, nil
		}

		r.logger.ErrorCtx(ctx, "cannot check document access", log.Error(err))

		return false, gqlutils.Internal(ctx)
	}

	return documentAccess.Status == coredata.CompliancePortalDocumentAccessStatusGranted, nil
}

// Access is the resolver for the access field.
func (r *documentResolver) Access(ctx context.Context, obj *types.Document) (*types.DocumentAccess, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, nil // User is not authenticated, so no access requested
	}

	access, err := visitorService.GetPortalDocumentAccess(
		ctx, scope,
		compliancePortal.ID,
		identity.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrMembershipNotFound) ||
			errors.Is(err, visitor.ErrUserNotFound) ||
			errors.Is(err, visitor.ErrDocumentAccessNotFound) {
			return nil, nil
		}

		if errors.Is(err, visitor.ErrUserInactive) {
			return nil, gqlutils.Forbidden(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get document access", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DocumentAccess{
		ID:     access.ID,
		Status: access.Status,
	}, nil
}

// LightLogo is the resolver for the lightLogo field.
func (r *frameworkResolver) LightLogo(ctx context.Context, obj *types.Framework) (*types.File, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	framework, err := r.visitor.GetFrameworkForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrFrameworkNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "framework %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load framework", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if framework.LightLogoFileID == nil {
		return nil, nil
	}

	return r.loadPublicFile(ctx, *framework.LightLogoFileID)
}

// DarkLogo is the resolver for the darkLogo field.
func (r *frameworkResolver) DarkLogo(ctx context.Context, obj *types.Framework) (*types.File, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	framework, err := r.visitor.GetFrameworkForCompliancePortalID(
		ctx,
		scope,
		compliancePortal.ID,
		obj.ID,
	)
	if err != nil {
		if errors.Is(err, visitor.ErrFrameworkNotFound) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "framework %q not found", obj.ID)
		}

		r.logger.ErrorCtx(ctx, "cannot load framework", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if framework.DarkLogoFileID == nil {
		return nil, nil
	}

	return r.loadPublicFile(ctx, *framework.DarkLogoFileID)
}

// ExportDocumentPDF is the resolver for the exportDocumentPDF field.
func (r *mutationResolver) ExportDocumentPDF(ctx context.Context, input types.ExportDocumentPDFInput) (*types.ExportDocumentPDFPayload, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	_, portalDocument, err := visitorService.GetDocument(ctx, scope, compliancePortal.ID, input.DocumentID)
	if err != nil {
		if errors.Is(err, visitor.ErrDocumentNotFound) || errors.Is(err, visitor.ErrDocumentNotVisible) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "document %q not found", input.DocumentID)
		}

		if _, ok := errors.AsType[*visitor.ErrDocumentArchived](err); ok {
			return nil, gqlutils.NotFoundf(ctx, "document %q not found", input.DocumentID)
		}

		r.logger.ErrorCtx(ctx, "cannot load document", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if portalDocument.Visibility == coredata.CompliancePortalVisibilityPublic {
		pdf, err := visitorService.ExportDocumentPDFWithoutWatermark(ctx, scope, compliancePortal.ID, input.DocumentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot export document PDF", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &types.ExportDocumentPDFPayload{
			Data: fmt.Sprintf("data:application/pdf;base64,%s", base64.StdEncoding.EncodeToString(pdf)),
		}, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticated(ctx, errors.New("unauthenticated"))
	}

	if err := r.requireCompletedNDA(ctx); err != nil {
		return nil, err
	}

	documentAccess, err := visitorService.GetPortalDocumentAccess(
		ctx, scope,
		compliancePortal.ID,
		identity.ID,
		input.DocumentID,
	)
	if err != nil {
		return nil, nil
	}

	if documentAccess.Status != coredata.CompliancePortalDocumentAccessStatusGranted {
		return nil, gqlutils.Forbiddenf(ctx, "access denied: no permission to access this document")
	}

	pdf, err := visitorService.ExportDocumentPDF(ctx, scope, compliancePortal.ID, input.DocumentID, identity.EmailAddress)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot export document PDF", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.ExportDocumentPDFPayload{
		Data: fmt.Sprintf("data:application/pdf;base64,%s", base64.StdEncoding.EncodeToString(pdf)),
	}, nil
}

// ExportReportPDF is the resolver for the exportReportPDF field.
func (r *mutationResolver) ExportReportPDF(ctx context.Context, input types.ExportReportPDFInput) (*types.ExportReportPDFPayload, error) {
	visitorService := r.visitor
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)

	_, portalAudit, err := visitorService.GetAuditByReportFileID(ctx, scope, compliancePortal.ID, input.ReportID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, visitor.ErrReportNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "report %q not found", input.ReportID)
		}

		r.logger.ErrorCtx(ctx, "cannot load audit", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if portalAudit.Visibility == coredata.CompliancePortalVisibilityPublic {
		pdf, err := visitorService.ExportReportPDFWithoutWatermark(ctx, scope, input.ReportID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot export report PDF", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &types.ExportReportPDFPayload{
			Data: fmt.Sprintf("data:application/pdf;base64,%s", base64.StdEncoding.EncodeToString(pdf)),
		}, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "unauthenticated")
	}

	if err := r.requireCompletedNDA(ctx); err != nil {
		return nil, err
	}

	reportAccess, err := visitorService.GetPortalReportFileAccess(
		ctx, scope,
		compliancePortal.ID,
		identity.ID,
		input.ReportID,
	)
	if err != nil {
		return nil, nil
	}

	if reportAccess.Status != coredata.CompliancePortalDocumentAccessStatusGranted {
		return nil, gqlutils.Forbiddenf(ctx, "access denied: no permission to access this report")
	}

	pdf, err := visitorService.ExportReportPDF(ctx, scope, input.ReportID, identity.EmailAddress)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot export report PDF", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.ExportReportPDFPayload{
		Data: fmt.Sprintf("data:application/pdf;base64,%s", base64.StdEncoding.EncodeToString(pdf)),
	}, nil
}

// ExportCompliancePortalFile is the resolver for the exportCompliancePortalFile field.
func (r *mutationResolver) ExportCompliancePortalFile(ctx context.Context, input types.ExportCompliancePortalFileInput) (*types.ExportCompliancePortalFilePayload, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)
	visitorService := r.visitor

	portalFile, err := visitorService.GetPortalFile(ctx, scope, compliancePortal.ID, input.CompliancePortalFileID)
	if err != nil {
		if errors.Is(err, visitor.ErrPortalFileNotFound) || errors.Is(err, visitor.ErrPortalFileNotVisible) {
			return nil, gqlutils.NotFoundf(ctx, "compliance portal file %q not found", input.CompliancePortalFileID)
		}

		r.logger.ErrorCtx(ctx, "cannot load compliance portal file", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if portalFile.CompliancePortalVisibility == coredata.CompliancePortalVisibilityPublic {
		fileData, mimeType, err := visitorService.ExportPortalFileWithoutWatermark(ctx, scope, input.CompliancePortalFileID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot export compliance portal file", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &types.ExportCompliancePortalFilePayload{
			Data: fmt.Sprintf("data:%s;base64,%s", mimeType, base64.StdEncoding.EncodeToString(fileData)),
		}, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "unauthenticated")
	}

	if err := r.requireCompletedNDA(ctx); err != nil {
		return nil, err
	}

	fileAccess, err := visitorService.GetPortalFileAccess(ctx, scope,
		compliancePortal.ID,
		identity.ID,
		input.CompliancePortalFileID,
	)
	if err != nil {
		return nil, nil
	}

	if fileAccess.Status != coredata.CompliancePortalDocumentAccessStatusGranted {
		return nil, gqlutils.Forbiddenf(ctx, "access denied: no permission to access this file")
	}

	fileData, mimeType, err := visitorService.ExportPortalFile(ctx, scope, input.CompliancePortalFileID, identity.EmailAddress)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot export compliance portal file", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.ExportCompliancePortalFilePayload{
		Data: fmt.Sprintf("data:%s;base64,%s", mimeType, base64.StdEncoding.EncodeToString(fileData)),
	}, nil
}

// RequestDocumentAccess is the resolver for the requestDocumentAccess field.
func (r *mutationResolver) RequestDocumentAccess(ctx context.Context, input types.RequestDocumentAccessInput) (*types.RequestDocumentAccessPayload, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)
	visitorService := r.visitor

	document, portalDocument, err := visitorService.GetDocument(ctx, scope, compliancePortal.ID, input.DocumentID)
	if err != nil {
		if errors.Is(err, visitor.ErrDocumentNotFound) || errors.Is(err, visitor.ErrDocumentNotVisible) || errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "document %q not found", input.DocumentID)
		}

		if _, ok := errors.AsType[*visitor.ErrDocumentArchived](err); ok {
			return nil, gqlutils.NotFoundf(ctx, "document %q not found", input.DocumentID)
		}

		r.logger.ErrorCtx(ctx, "cannot load document", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if portalDocument.Visibility == coredata.CompliancePortalVisibilityPublic {
		return nil, gqlutils.Invalidf(
			ctx,
			"document is publicly available and does not require access request",
		)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to request access")
	}

	if _, err := visitorService.RequestPortalAccess(
		ctx, scope,
		&visitor.PortalAccessRequest{
			CompliancePortalID:      compliancePortal.ID,
			IdentityID:              identity.ID,
			DocumentIDs:             []gid.GID{input.DocumentID},
			ReportIDs:               []gid.GID{},
			CompliancePortalFileIDs: []gid.GID{},
		},
	); err != nil {
		r.logger.ErrorCtx(ctx, "cannot request document access", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.RequestDocumentAccessPayload{
		Document: types.NewDocument(document),
	}, nil
}

// RequestReportAccess is the resolver for the requestReportAccess field.
func (r *mutationResolver) RequestReportAccess(ctx context.Context, input types.RequestReportAccessInput) (*types.RequestReportAccessPayload, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)
	visitorService := r.visitor

	audit, portalAudit, err := visitorService.GetAuditByReportFileID(ctx, scope, compliancePortal.ID, input.ReportID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, visitor.ErrReportNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "report %q not found", input.ReportID)
		}

		r.logger.ErrorCtx(ctx, "cannot load audit", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if portalAudit.Visibility == coredata.CompliancePortalVisibilityPublic {
		return nil, gqlutils.Invalidf(
			ctx,
			"report is publicly available and does not require access request",
		)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to request access")
	}

	if _, err := visitorService.RequestPortalAccess(
		ctx, scope,
		&visitor.PortalAccessRequest{
			CompliancePortalID:      compliancePortal.ID,
			IdentityID:              identity.ID,
			DocumentIDs:             []gid.GID{},
			ReportIDs:               []gid.GID{input.ReportID},
			CompliancePortalFileIDs: []gid.GID{},
		},
	); err != nil {
		r.logger.ErrorCtx(ctx, "cannot request report access", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.RequestReportAccessPayload{
		Audit: types.NewAudit(audit),
	}, nil
}

// RequestCompliancePortalFileAccess is the resolver for the requestCompliancePortalFileAccess field.
func (r *mutationResolver) RequestCompliancePortalFileAccess(ctx context.Context, input types.RequestCompliancePortalFileAccessInput) (*types.RequestFileAccessPayload, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)
	visitorService := r.visitor

	portalFile, err := visitorService.GetPortalFile(ctx, scope, compliancePortal.ID, input.CompliancePortalFileID)
	if err != nil {
		if errors.Is(err, visitor.ErrPortalFileNotFound) || errors.Is(err, visitor.ErrPortalFileNotVisible) {
			return nil, gqlutils.NotFoundf(ctx, "compliance portal file %q not found", input.CompliancePortalFileID)
		}

		r.logger.ErrorCtx(ctx, "cannot load compliance portal file", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if portalFile.CompliancePortalVisibility == coredata.CompliancePortalVisibilityPublic {
		return nil, gqlutils.Invalidf(
			ctx,
			"compliance portal file is publicly available and does not require access request",
		)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to request access")
	}

	if _, err := visitorService.RequestPortalAccess(
		ctx, scope,
		&visitor.PortalAccessRequest{
			CompliancePortalID:      compliancePortal.ID,
			IdentityID:              identity.ID,
			DocumentIDs:             []gid.GID{},
			ReportIDs:               []gid.GID{},
			CompliancePortalFileIDs: []gid.GID{input.CompliancePortalFileID},
		},
	); err != nil {
		r.logger.ErrorCtx(ctx, "cannot request compliance portal file access", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.RequestFileAccessPayload{
		File: types.NewCompliancePortalFile(portalFile),
	}, nil
}

// RequestAccesses is the resolver for the requestAccesses field.
func (r *mutationResolver) RequestAccesses(ctx context.Context, input types.RequestAccessesInput) (*types.RequestAccessesResultPayload, error) {
	compliancePortal := complianceportal.CompliancePortalFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePortal.ID)
	visitorService := r.visitor

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to request access")
	}

	if len(input.DocumentIds) == 0 && len(input.ReportIds) == 0 && len(input.CompliancePortalFileIds) == 0 {
		return nil, gqlutils.Invalidf(ctx, "at least one document, report, or file id is required")
	}

	// Load and validate every target before requesting so a foreign, invisible,
	// or public GID is handled before any access row is written (mirrors the
	// per-resource resolvers, which load and guard ahead of the request). Only
	// the resolved, non-public ids are forwarded to RequestPortalAccess.
	payload := &types.RequestAccessesResultPayload{
		Documents: make([]*types.Document, 0, len(input.DocumentIds)),
		Audits:    make([]*types.Audit, 0, len(input.ReportIds)),
		Files:     make([]*types.CompliancePortalFile, 0, len(input.CompliancePortalFileIds)),
	}

	requestDocumentIDs := make([]gid.GID, 0, len(input.DocumentIds))
	requestReportIDs := make([]gid.GID, 0, len(input.ReportIds))
	requestFileIDs := make([]gid.GID, 0, len(input.CompliancePortalFileIds))

	for _, documentID := range input.DocumentIds {
		document, portalDocument, err := visitorService.GetDocument(ctx, scope, compliancePortal.ID, documentID)
		if err != nil {
			if errors.Is(err, visitor.ErrDocumentNotFound) || errors.Is(err, visitor.ErrDocumentNotVisible) || errors.Is(err, coredata.ErrResourceNotFound) {
				return nil, gqlutils.NotFoundf(ctx, "document %q not found", documentID)
			}

			if _, ok := errors.AsType[*visitor.ErrDocumentArchived](err); ok {
				return nil, gqlutils.NotFoundf(ctx, "document %q not found", documentID)
			}

			r.logger.ErrorCtx(ctx, "cannot load document", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}

		// Public resources are already accessible; skip them so no needless
		// REQUESTED row is created (mirrors the per-resource resolver's guard).
		if portalDocument.Visibility == coredata.CompliancePortalVisibilityPublic {
			continue
		}

		requestDocumentIDs = append(requestDocumentIDs, documentID)
		payload.Documents = append(payload.Documents, types.NewDocument(document))
	}

	for _, reportID := range input.ReportIds {
		audit, portalAudit, err := visitorService.GetAuditByReportFileID(ctx, scope, compliancePortal.ID, reportID)
		if err != nil {
			if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, visitor.ErrReportNotFound) {
				return nil, gqlutils.NotFoundf(ctx, "report %q not found", reportID)
			}

			r.logger.ErrorCtx(ctx, "cannot load audit", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}

		if portalAudit.Visibility == coredata.CompliancePortalVisibilityPublic {
			continue
		}

		requestReportIDs = append(requestReportIDs, reportID)
		payload.Audits = append(payload.Audits, types.NewAudit(audit))
	}

	for _, fileID := range input.CompliancePortalFileIds {
		portalFile, err := visitorService.GetPortalFile(ctx, scope, compliancePortal.ID, fileID)
		if err != nil {
			if errors.Is(err, visitor.ErrPortalFileNotFound) || errors.Is(err, visitor.ErrPortalFileNotVisible) {
				return nil, gqlutils.NotFoundf(ctx, "compliance portal file %q not found", fileID)
			}

			r.logger.ErrorCtx(ctx, "cannot load compliance portal file", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}

		if portalFile.CompliancePortalVisibility == coredata.CompliancePortalVisibilityPublic {
			continue
		}

		requestFileIDs = append(requestFileIDs, fileID)
		payload.Files = append(payload.Files, types.NewCompliancePortalFile(portalFile))
	}

	// All supplied ids were public (already accessible); nothing to request.
	if len(requestDocumentIDs) == 0 && len(requestReportIDs) == 0 && len(requestFileIDs) == 0 {
		return payload, nil
	}

	if _, err := visitorService.RequestPortalAccess(
		ctx, scope,
		&visitor.PortalAccessRequest{
			CompliancePortalID:      compliancePortal.ID,
			IdentityID:              identity.ID,
			DocumentIDs:             requestDocumentIDs,
			ReportIDs:               requestReportIDs,
			CompliancePortalFileIDs: requestFileIDs,
		},
	); err != nil {
		if errors.Is(err, visitor.ErrNoAccessTargets) {
			return nil, gqlutils.Invalidf(ctx, "at least one document, report, or file id is required")
		}

		r.logger.ErrorCtx(ctx, "cannot request accesses", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return payload, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *subprocessorConnectionResolver) TotalCount(ctx context.Context, obj *types.SubprocessorConnection) (int, error) {
	scope := coredata.NewScopeFromObjectID(obj.ParentID)
	visitorService := r.visitor

	switch obj.Resolver.(type) {
	case *compliancePortalResolver:
		count, err := visitorService.CountThirdPartiesForCompliancePortalID(ctx, scope, obj.ParentID, obj.Filter)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count subprocessors", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	}

	r.logger.ErrorCtx(ctx, "not implemented: TotalCount for parent type")

	return 0, gqlutils.Internal(ctx)
}

// Audit returns schema.AuditResolver implementation.
func (r *Resolver) Audit() schema.AuditResolver { return &auditResolver{r} }

// AuditReport returns schema.AuditReportResolver implementation.
func (r *Resolver) AuditReport() schema.AuditReportResolver { return &auditReportResolver{r} }

// ComplianceFramework returns schema.ComplianceFrameworkResolver implementation.
func (r *Resolver) ComplianceFramework() schema.ComplianceFrameworkResolver {
	return &complianceFrameworkResolver{r}
}

// CompliancePortal returns schema.CompliancePortalResolver implementation.
func (r *Resolver) CompliancePortal() schema.CompliancePortalResolver {
	return &compliancePortalResolver{r}
}

// CompliancePortalCommitmentGroup returns schema.CompliancePortalCommitmentGroupResolver implementation.
func (r *Resolver) CompliancePortalCommitmentGroup() schema.CompliancePortalCommitmentGroupResolver {
	return &compliancePortalCommitmentGroupResolver{r}
}

// CompliancePortalFile returns schema.CompliancePortalFileResolver implementation.
func (r *Resolver) CompliancePortalFile() schema.CompliancePortalFileResolver {
	return &compliancePortalFileResolver{r}
}

// CompliancePortalReference returns schema.CompliancePortalReferenceResolver implementation.
func (r *Resolver) CompliancePortalReference() schema.CompliancePortalReferenceResolver {
	return &compliancePortalReferenceResolver{r}
}

// Document returns schema.DocumentResolver implementation.
func (r *Resolver) Document() schema.DocumentResolver { return &documentResolver{r} }

// Framework returns schema.FrameworkResolver implementation.
func (r *Resolver) Framework() schema.FrameworkResolver { return &frameworkResolver{r} }

// SubprocessorConnection returns schema.SubprocessorConnectionResolver implementation.
func (r *Resolver) SubprocessorConnection() schema.SubprocessorConnectionResolver {
	return &subprocessorConnectionResolver{r}
}

type (
	auditResolver                           struct{ *Resolver }
	auditReportResolver                     struct{ *Resolver }
	complianceFrameworkResolver             struct{ *Resolver }
	compliancePortalResolver                struct{ *Resolver }
	compliancePortalCommitmentGroupResolver struct{ *Resolver }
	compliancePortalFileResolver            struct{ *Resolver }
	compliancePortalReferenceResolver       struct{ *Resolver }
	documentResolver                        struct{ *Resolver }
	frameworkResolver                       struct{ *Resolver }
	subprocessorConnectionResolver          struct{ *Resolver }
)
