package templates

func iso42001Pack() Pack {
  templates := []TemplateDefinition{
    tmpl("aims-scope", "AIMS-4.3", "AI Management System Scope", "governance document", "AI Governance", "GOVERNANCE", "roles.ai_owner",
      "Define the organisational boundaries, AI-related activities, systems, products/services, roles and locations covered by the AI management system.",
      []string{
        "The AIMS covers AI systems developed, procured, configured or materially used by {{organization.legal_name}} in support of {{organization.services}} across {{organization.locations}} where they can affect organisational objectives, people, customers, obligations or risk.",
        "The scope considers internal/external context, relevant interested parties, applicable legal/contractual obligations, AI lifecycle activities and interfaces with suppliers or customers.",
        "The scope is reviewed after material change to AI systems, purposes, data, suppliers, regulation, organisational structure or risk.",
      },
      []string{"Approved AIMS scope", "Current AI system/use inventory"},
      []string{"ISO/IEC 42001:2023 management-system scope"},
      []string{"AI systems/use cases in scope", "material outsourced AI activities and interfaces"}, nil),

    tmpl("ai-policy", "AIMS-5.2", "AI Management and Responsible Use Policy", "policy", "AI Governance", "POLICY", "roles.executive_owner",
      "Set management direction for responsible AI development/use, risk management, accountability, transparency and continual improvement.",
      []string{
        "{{organization.legal_name}} uses or develops AI only for defined and authorised purposes with accountable human ownership and controls proportionate to potential impact.",
        "AI risks and opportunities are assessed across the lifecycle, including impacts on people, security, privacy, quality, reliability, fairness, transparency, safety and legal/contractual obligations where relevant.",
        "Data, models, suppliers, changes and operational monitoring are governed so decisions remain traceable and issues can be detected and corrected.",
        "Meaningful human oversight is designed for use cases where automated outputs can create material consequences or where risk requires intervention.",
        "AI incidents, complaints, performance failures and emerging risks are reported and used to improve the AIMS.",
      },
      []string{"Approved AI policy", "Evidence policy was communicated"},
      []string{"ISO/IEC 42001:2023 leadership and policy requirements"},
      []string{"organisation-specific responsible-AI principles", "senior management approval"}, nil),

    tmpl("ai-roles", "AIMS-5.3", "AI Governance Roles and Responsibility Matrix", "register", "AI Governance", "REGISTER", "roles.ai_owner",
      "Assign accountability for AI system ownership, risk, data, technical assurance, legal/privacy review, human oversight, incident response and approval.",
      []string{
        "Every material AI system or use case has a named business/system owner accountable for purpose, approved use and lifecycle decisions.",
        "Responsibilities for model/technical performance, data governance, security, privacy/legal review and human oversight are assigned according to the use case and organisational structure.",
        "Material conflicts of interest and segregation needs are considered for approval, testing and independent assurance.",
        "Roles and deputies are reviewed after organisational or system change.",
      },
      []string{"AI governance role matrix", "Relevant role/approval evidence"},
      []string{"ISO/IEC 42001:2023 roles and responsibilities"},
      []string{"AI approval authority", "model/data/security/privacy owners where applicable", "human-review escalation owner"}, nil),

    confidential(tmpl("ai-inventory", "AIMS-INVENTORY", "AI Systems and Use Case Inventory", "register", "AI Inventory", "REGISTER", "roles.ai_owner",
      "Maintain an authoritative inventory of AI systems and material AI-enabled use cases with ownership, purpose, data, suppliers, risk and lifecycle status.",
      []string{
        "Record system/use-case name, owner, purpose, users/affected people, lifecycle status, deployment context, provider/model where known, material data categories, integrations and decision/support role.",
        "Record risk/impact classification, relevant assessments, supplier dependencies, monitoring, human oversight and approval status.",
        "Inventory entries are reviewed when purpose, model/provider, data, integrations, affected people, output use or risk changes materially.",
      },
      []string{"Current AI inventory", "System approval/assessment links"},
      []string{"ISO/IEC 42001:2023 AI system/resource and lifecycle governance"},
      []string{"all material AI systems/use cases"}, nil)),

    confidential(tmpl("intended-use", "AIMS-PURPOSE", "AI Intended Purpose and Use Record", "record", "AI Lifecycle", "RECORD", "roles.ai_owner",
      "Document what an AI system is intended to do, who will use it, who may be affected, boundaries, assumptions and prohibited uses before approval.",
      []string{
        "Define business purpose, expected benefits, users, affected parties, input/output role and whether the AI informs or makes decisions.",
        "Document conditions, limitations, assumptions, required human review and situations where outputs must not be used without additional verification.",
        "Identify reasonably foreseeable misuse and prohibited use where material to risk.",
        "Reapprove the intended-use record after material purpose or deployment-context change.",
      },
      []string{"Approved intended-purpose/use record", "User instructions or operating guidance"},
      []string{"Supports ISO/IEC 42001:2023 AI lifecycle and responsible-use controls"},
      []string{"purpose, users/affected people, decision role, limitations and prohibited uses"}, nil)),

    confidential(tmpl("ai-impact", "AIMS-IMPACT", "AI System Impact Assessment", "assessment", "AI Risk and Impact", "TEMPLATE", "roles.ai_owner",
      "Assess intended and reasonably foreseeable impacts on individuals, groups, society, customers and the organisation before material AI use.",
      []string{
        "Describe system purpose, context, stakeholders, affected people, decision significance, data, deployment scale and dependencies.",
        "Assess potential beneficial and adverse impacts, including fairness/discrimination, accessibility, autonomy, privacy, security, safety, financial/opportunity effects, service quality, transparency and contestability where relevant.",
        "Consider severity, likelihood, reversibility, scale and vulnerability/power imbalance, then define mitigations and responsible owners.",
        "Record residual-impact acceptance and review triggers and seek affected/expert input where useful and proportionate.",
      },
      []string{"Approved AI impact assessment", "Evidence mitigations were implemented"},
      []string{"ISO/IEC 42001:2023 AI impact assessment and risk management"},
      []string{"stakeholders/affected groups", "impact ratings", "mitigations and residual approval"}, nil)),

    confidential(tmpl("ai-risk", "AIMS-6.1", "AI Risk and Opportunity Register", "register", "AI Risk and Impact", "REGISTER", "roles.ai_owner",
      "Identify and track AI-specific risks and opportunities through treatment, monitoring and residual acceptance.",
      []string{
        "Risk scenarios consider intended use, foreseeable misuse, model/output errors, harmful bias, data problems, security/privacy, insufficient transparency, human over-reliance, supplier dependency, drift, availability and legal/contractual issues where relevant.",
        "Assess likelihood and impact using the approved risk method and assign an accountable owner.",
        "Treatment records controls/actions, target dates, evidence, residual risk and acceptance authority.",
        "Reassess after material model/data/purpose/provider change, incident, regulatory change or monitoring signal.",
      },
      []string{"AI risk register", "Treatment/residual-risk approvals"},
      []string{"ISO/IEC 42001:2023 risk and opportunity management"},
      []string{"priority AI risks and risk appetite/acceptance authority"},
      []string{"Incorrect or fabricated output influences a material decision", "Training/input data creates unfair or unrepresentative outcomes", "Sensitive information is exposed through input/output/provider processing", "Model/provider change alters performance without adequate validation", "Users over-rely on AI output without required verification", "Supplier outage or service change disrupts a critical AI-enabled process"})),

    confidential(tmpl("ai-data", "AIMS-DATA", "AI Data Governance and Quality Assessment", "assessment", "AI Data", "TEMPLATE", "roles.ai_owner",
      "Assess whether data used to develop, evaluate or operate an AI system is suitable, governed, lawful and sufficiently representative/accurate for its purpose.",
      []string{
        "Identify data sources, ownership/licensing, collection/provenance, personal/sensitive information, permitted purpose and relevant retention/security constraints.",
        "Define quality characteristics important to the use case such as completeness, accuracy, relevance, timeliness, consistency, representativeness and known limitations.",
        "Assess bias or coverage gaps relevant to affected groups and intended deployment and document mitigation or limitations.",
        "Data changes that can materially affect system behaviour trigger reassessment and testing.",
      },
      []string{"AI data assessment", "Data provenance/quality evidence", "Privacy/lawful-use evidence where relevant"},
      []string{"ISO/IEC 42001:2023 data governance/resource controls"},
      []string{"data sources/provenance", "quality criteria", "known limitations and representation gaps"}, nil)),

    tmpl("human-oversight", "AIMS-OVERSIGHT", "Human Oversight and Intervention Plan", "plan", "AI Operations", "PLAN", "roles.ai_owner",
      "Define when and how people review, override, stop or escalate AI outputs and ensure reviewers have enough authority, information and competence.",
      []string{
        "Identify decisions or outputs requiring human review before action and the evidence/context the reviewer must consider.",
        "Reviewers are trained about system purpose, limitations, common failure modes and automation-bias risk and have authority to disagree, override or stop use.",
        "Escalation routes exist for uncertainty, harmful/incorrect output, complaints, material anomalies and situations outside intended use.",
        "Oversight effectiveness is monitored using outcomes, overrides, incidents, complaints and reviewer feedback.",
      },
      []string{"Human oversight plan", "Reviewer training/operating evidence", "Override/escalation records where available"},
      []string{"Supports ISO/IEC 42001:2023 human oversight and responsible-use controls"},
      []string{"outputs requiring review", "reviewer roles/authority", "stop/escalation conditions"}, nil),

    tmpl("transparency", "AIMS-TRANSPARENCY", "AI Transparency and User Information Notice", "notice", "AI Transparency", "TEMPLATE", "roles.ai_owner",
      "Give users or affected people proportionate information about relevant AI use, purpose, role, limitations and ways to seek help or challenge outcomes.",
      []string{
        "Explain when AI is materially involved, what purpose it serves and whether it supports or makes decisions in the relevant context.",
        "Describe important limitations, appropriate-use expectations and any required human verification in language suitable for the audience.",
        "Where relevant, explain available human review, correction, complaint or appeal routes and how to contact the organisation.",
        "Avoid claims about accuracy, fairness, safety or capability that cannot be supported by evidence.",
      },
      []string{"Published/approved AI transparency notice", "User instructions"},
      []string{"Supports ISO/IEC 42001:2023 transparency and information-for-interested-parties controls"},
      []string{"system/use-case specific disclosure, limitations and contact/review route"}, nil),

    confidential(tmpl("ai-supplier", "AIMS-SUPPLIER", "AI Supplier and Model Provider Assessment", "assessment", "AI Third Parties", "TEMPLATE", "roles.ai_owner",
      "Assess AI suppliers/providers, model services and externally provided components before use and throughout the relationship.",
      []string{
        "Assess provider capability, service/model purpose, data use/retention, security/privacy, locations, sub-processors, training-data or model information where relevant/available, assurance, performance, change notification, incident support and exit arrangements.",
        "Contractual or service terms define important responsibilities, permitted data/use, confidentiality, security, availability, change, incident, audit/assurance and deletion/exit expectations proportionate to risk.",
        "Provider/model changes are monitored and material changes trigger re-evaluation and testing.",
      },
      []string{"Completed AI supplier assessment", "Relevant contract/service terms", "Supplier assurance evidence"},
      []string{"ISO/IEC 42001:2023 supplier/external-party controls"},
      []string{"AI providers/models and minimum due-diligence evidence"}, nil)),

    confidential(tmpl("ai-evaluation", "AIMS-EVALUATION", "AI System Evaluation and Test Plan", "plan", "AI Assurance", "PLAN", "roles.ai_owner",
      "Define evidence-based tests and acceptance criteria for AI performance, limitations and risk controls before release and after material change.",
      []string{
        "Tests are derived from intended purpose, important risks, affected groups, operational context and quality/safety/security/privacy requirements.",
        "Evaluation datasets/scenarios are sufficiently relevant to intended deployment and known limitations or representation gaps are documented.",
        "Acceptance criteria and thresholds are approved before release where practical; failed material criteria block release or require documented risk acceptance and mitigation.",
        "Testing is repeated after material model, prompt/configuration, data, provider or integration change and results remain traceable to the tested version.",
      },
      []string{"AI test/evaluation plan", "Test results and release decision"},
      []string{"Supports ISO/IEC 42001:2023 performance evaluation and lifecycle controls"},
      []string{"metrics, test scenarios, acceptance thresholds and version identification"}, nil)),

    confidential(tmpl("fairness", "AIMS-FAIRNESS", "AI Fairness and Bias Assessment", "assessment", "AI Risk and Impact", "TEMPLATE", "roles.ai_owner",
      "Assess whether an AI system can create unjustified differences in outcomes or quality for relevant groups and document proportionate mitigation.",
      []string{
        "Identify groups or characteristics relevant to the use context and potential sources of bias in data, labels, objectives, model design, prompts, human interpretation or deployment.",
        "Select fairness/quality checks appropriate to the decision and available data rather than relying on one generic fairness metric.",
        "Investigate material disparities, assess legitimate/contextual explanations and implement mitigation or limitations where necessary.",
        "Monitor fairness-related outcomes and complaints after deployment where risk warrants ongoing review.",
      },
      []string{"Fairness/bias assessment", "Testing/monitoring evidence"},
      []string{"Supports ISO/IEC 42001:2023 impact, responsible-use and performance controls"},
      []string{"relevant groups, fairness criteria and material findings"}, nil)),

    confidential(tmpl("ai-security", "AIMS-SECURITY", "AI Security and Abuse Assessment", "assessment", "AI Security", "TEMPLATE", "roles.security_owner",
      "Assess threats and misuse scenarios specific to AI systems and integrate treatment with the organisation's information-security controls.",
      []string{
        "Consider unauthorised access, sensitive-data leakage, prompt/instruction manipulation, malicious inputs, model or data poisoning where relevant, insecure integrations, excessive permissions, extraction/abuse, denial of service and unsafe tool/action execution.",
        "Apply authentication, authorisation, data minimisation, isolation, validation, monitoring, secure configuration and other controls proportionate to the architecture and risk.",
        "Security testing and abuse-case evaluation are repeated after material architecture/provider/capability change.",
      },
      []string{"AI security/abuse assessment", "Security test/configuration evidence"},
      []string{"ISO/IEC 42001:2023 risk and AI system lifecycle controls", "ISO/IEC 27001 integration where applicable"},
      []string{"AI threat scenarios, integrations/tools and security controls"}, nil)),

    confidential(tmpl("ai-incident", "AIMS-INCIDENT", "AI Incident and Harm Response Procedure", "procedure", "AI Operations", "PROCEDURE", "roles.ai_owner",
      "Identify, contain, investigate and learn from AI failures, harmful outputs, misuse, significant performance degradation and related complaints.",
      []string{
        "Define events that require AI-incident escalation, including harmful/incorrect outputs, unauthorised use, data/security events, systemic bias, significant drift, safety issues or loss of required human oversight.",
        "Response actions can include disabling or restricting the system/use case, reverting versions/configuration, preserving evidence, notifying relevant internal/external stakeholders and providing human alternatives/remediation.",
        "Investigate root cause and affected versions/users, assess legal/privacy/security obligations and track corrective actions.",
        "Lessons learned update risk, impact assessment, tests, monitoring, training, instructions and supplier controls.",
      },
      []string{"AI incident procedure/register", "Completed incident or exercise record"},
      []string{"ISO/IEC 42001:2023 operational control, monitoring and improvement"},
      []string{"AI incident severity/escalation and stop-use authority"}, nil)),

    tmpl("ai-change", "AIMS-CHANGE", "AI Change and Version Management Procedure", "procedure", "AI Lifecycle", "PROCEDURE", "roles.ai_owner",
      "Control changes to models, providers, prompts/configuration, data, tools/integrations and use context so risk and performance remain understood.",
      []string{
        "Material change criteria include model/provider version, fine-tuning/training data, system prompts/configuration, retrieval/data sources, integrations/tools, decision significance, purpose, user group and deployment environment.",
        "Before material change, determine which impact/risk/data/security/privacy/fairness/test records require review and approval.",
        "Maintain sufficient version traceability to understand what configuration produced important outcomes and to support rollback where practical.",
        "Emergency changes are controlled and retrospectively reviewed.",
      },
      []string{"AI change records", "Reassessment/test evidence"},
      []string{"ISO/IEC 42001:2023 lifecycle/change management"},
      []string{"material change triggers and approval authority"}, nil),

    confidential(tmpl("ai-monitoring", "AIMS-MONITORING", "AI Performance and Drift Monitoring Plan", "plan", "AI Performance", "PLAN", "roles.ai_owner",
      "Monitor operational AI performance, risk indicators, drift, complaints and control effectiveness against approved expectations.",
      []string{
        "Define metrics/signals relevant to intended purpose and risk, such as quality/accuracy proxies, failure/hallucination rates where measurable, overrides, complaints, fairness indicators, safety/security events, latency/availability and data/model drift.",
        "Set monitoring frequency, thresholds and responsible owners proportionate to system impact and rate of change.",
        "Threshold breaches trigger investigation, human review, restriction, rollback, retraining/reconfiguration or reassessment as appropriate.",
        "Monitoring limitations and blind spots are documented rather than presenting metrics as complete assurance.",
      },
      []string{"AI monitoring plan", "Recent monitoring report", "Investigation/action evidence for material alerts"},
      []string{"ISO/IEC 42001:2023 monitoring, measurement, analysis and evaluation"},
      []string{"system-specific metrics, thresholds and monitoring frequency"}, nil)),

    tmpl("ai-decommission", "AIMS-DECOMMISSION", "AI System Decommissioning and Exit Plan", "plan", "AI Lifecycle", "PLAN", "roles.ai_owner",
      "Retire AI systems or providers safely while addressing data, access, records, customer/user dependencies and ongoing obligations.",
      []string{
        "Identify affected processes/users, replacement/manual alternatives, data/export needs, contractual exit, records/evidence retention and communication requirements.",
        "Remove or revoke system/API access, keys/secrets and integrations; return/delete data according to legal/contractual requirements and verify provider exit obligations where possible.",
        "Retain enough version, decision, incident and assessment evidence to meet legitimate accountability, legal and operational needs.",
        "Confirm decommissioning completion and residual risks or dependencies.",
      },
      []string{"Decommission/exit record", "Access/data deletion or transfer evidence"},
      []string{"Supports ISO/IEC 42001:2023 AI lifecycle and supplier controls"},
      []string{"retention/exit obligations and replacement process"}, nil),

    tmpl("ai-training", "AIMS-COMPETENCE", "AI Competence and Awareness Plan", "plan", "People", "PLAN", "roles.ai_owner",
      "Ensure people who procure, build, configure, approve, operate or oversee AI systems understand their responsibilities and system limitations.",
      []string{
        "Role-based competence requirements reflect the person's decisions and potential impact, including technical, operational, risk, privacy/security, legal or human-oversight needs as relevant.",
        "General users receive practical guidance on authorised use, information handling, verification, limitations, escalation and prohibited uses.",
        "Training effectiveness is evaluated using practical evidence such as exercises, quality review, incident trends, observed misuse or knowledge checks.",
      },
      []string{"AI training plan", "Completion/competence evidence"},
      []string{"ISO/IEC 42001:2023 competence and awareness"},
      []string{"role groups, required training and refresher frequency"}, nil),

    tmpl("ai-objectives", "AIMS-6.2", "AI Management Objectives and KPI Register", "register", "AI Performance", "REGISTER", "roles.ai_owner",
      "Set measurable AI governance objectives and evaluate whether the AIMS is producing intended outcomes.",
      []string{
        "Objectives consider AI policy, risk/impact assessments, obligations, system performance, incidents, user/affected-person feedback and business priorities.",
        "Each objective has owner, target, resources, date and evaluation method and is reviewed when systems or risk change.",
      },
      []string{"AI objectives/KPI review"},
      []string{"ISO/IEC 42001:2023 objectives and performance evaluation"},
      []string{"targets and reporting frequency"},
      []string{"Material AI systems inventoried and risk-assessed", "High-impact use cases have approved impact assessment and oversight", "AI changes receive required re-evaluation before release", "AI incidents/complaints are closed with lessons learned", "Monitoring thresholds are reviewed and material alerts investigated on time"}),

    tmpl("ai-audit", "AIMS-9.2", "AI Management System Internal Audit Checklist and Report", "audit document", "Assurance", "REPORT", "roles.ai_owner",
      "Provide an audit structure for AI governance, lifecycle controls, risk/impact management and operational evidence.",
      []string{
        "Audit scope and criteria cover the AIMS, selected AI systems/use cases, internal arrangements and relevant legal/contractual commitments.",
        "Sample evidence across inventory, ownership, intended use, impact/risk, data, supplier, testing, human oversight, transparency, monitoring, incidents and changes.",
        "Record objective findings and track corrective action to verified closure.",
      },
      []string{"Completed AIMS audit report", "Evidence and findings"},
      []string{"ISO/IEC 42001:2023 internal audit"},
      []string{"audit scope, systems sampled and auditor(s)"},
      []string{"Scope/policy/roles", "AI inventory and intended use", "Impact/risk assessments", "Data governance", "Supplier controls", "Evaluation/testing", "Human oversight/transparency", "Security/privacy integration", "Change/version control", "Monitoring/incidents", "Improvement"}),

    confidential(tmpl("ai-management-review", "AIMS-9.3", "AI Management Review Agenda and Minutes", "record", "Governance", "RECORD", "roles.executive_owner",
      "Give senior management a ready agenda for AI governance performance, risk, change, resources and improvement decisions.",
      []string{
        "Review prior actions, context/interested-party/obligation changes, AI objectives, risk/impact status, significant system/provider changes, performance/monitoring, incidents/complaints, audits, resource/competence needs and improvement opportunities.",
        "Record decisions about risk acceptance, policy/control changes, resource needs, restrictions/retirement of systems and improvement actions.",
      },
      []string{"Approved AIMS management-review minutes", "Supporting AI performance/risk evidence"},
      []string{"ISO/IEC 42001:2023 management review"},
      []string{"meeting date, attendees, decisions and actions"}, nil)),

    tmpl("ai-corrective", "AIMS-10", "AI Nonconformity and Corrective Action Form", "form", "Improvement", "TEMPLATE", "roles.ai_owner",
      "Provide a consistent record for AI governance failures, correction, cause, system/control change and effectiveness review.",
      []string{
        "Record the nonconformity/failure, affected system/version/use, evidence and actual/potential impact.",
        "Take immediate correction/containment, assess similar risks and identify root/systemic cause where appropriate.",
        "Implement corrective actions with owners/dates and verify effectiveness through testing, monitoring, review or other suitable evidence.",
        "Update risk/impact assessments, system instructions, controls, training and supplier arrangements where the issue reveals a wider weakness.",
      },
      []string{"Completed AI corrective-action record"},
      []string{"ISO/IEC 42001:2023 nonconformity, corrective action and continual improvement"},
      []string{"closure authority for material AI corrective actions"}, nil),
  }

  return makePack(
    "iso42001",
    "Comp Plus+ ISO/IEC 42001 Fast Start",
    "2026.08.07",
    "ISO/IEC 42001:2023",
    "Ready-made AI governance, inventory, impact, risk, data, human oversight, supplier, evaluation, fairness, security, monitoring, incident, change and lifecycle templates for the current AI management-system standard.",
    templates,
    false,
    nil,
  )
}
