package templates

func iso9001Pack() Pack {
  templates := []TemplateDefinition{
    tmpl("qms-scope", "QMS-4.3", "Quality Management System Scope", "governance document", "QMS Governance", "GOVERNANCE", "roles.quality_owner",
      "Define the boundaries and applicability of the quality management system, including services, locations and justified non-applicable requirements.",
      []string{
        "The QMS covers the people, processes, resources and external providers used by {{organization.legal_name}} to deliver {{organization.services}} across {{organization.locations}}.",
        "The scope is based on organisational context, relevant interested-party requirements and the products/services provided.",
        "Any requirement determined not applicable is justified and cannot undermine the organisation's ability or responsibility to provide conforming products/services and enhance customer satisfaction.",
      },
      []string{"Approved QMS scope", "Current service/process/location information"},
      []string{"ISO 9001:2015 clause 4.3", "ISO 9001:2015/Amd 1:2024 context update"},
      []string{"products/services and sites in scope", "any non-applicable requirement and justification"}, nil),

    tmpl("quality-policy", "QMS-5.2", "Quality Policy", "policy", "QMS Governance", "POLICY", "roles.executive_owner",
      "Set management direction for quality, customer focus, applicable requirements and continual improvement.",
      []string{
        "{{organization.legal_name}} is committed to consistently meeting agreed customer, statutory, regulatory and contractual requirements for {{organization.services}}.",
        "Quality objectives are established, monitored and reviewed so performance and customer experience can be improved using evidence.",
        "Processes are managed using risk-based thinking, competent people, suitable resources and controlled information.",
        "Problems, complaints, nonconforming outputs and improvement opportunities are recorded and acted on proportionately.",
        "The QMS and this policy are continually improved as the organisation, customers, technology and obligations change.",
      },
      []string{"Approved quality policy", "Evidence policy was communicated"},
      []string{"ISO 9001:2015 clauses 5.1-5.2"},
      []string{"senior management approval", "how the policy is communicated and made available"}, nil),

    tmpl("process-map", "QMS-4.4", "QMS Process Map and Process Register", "register", "Process Management", "REGISTER", "roles.quality_owner",
      "Identify the QMS processes, inputs, outputs, sequence, interactions, owners, resources, criteria, risks and performance measures.",
      []string{
        "Each process has a named owner and a defined purpose, inputs, key activities, outputs and customers/receivers.",
        "Process interactions and dependencies are recorded so hand-offs and control points are clear.",
        "Criteria and methods for effective operation, monitoring and control are defined proportionate to process risk and importance.",
        "Resources, responsibilities, risks/opportunities and improvement actions are maintained for each material process.",
      },
      []string{"Current process map/register", "Process performance evidence"},
      []string{"ISO 9001:2015 clause 4.4"},
      []string{"core and support processes", "process owners and key KPIs"},
      []string{"Customer enquiry / requirements review", "Service planning and delivery", "Supplier/external provider management", "People and competence", "Document/record control", "Monitoring, complaints, audit and improvement"}),

    tmpl("quality-objectives", "QMS-6.2", "Quality Objectives and KPI Plan", "register", "QMS Performance", "REGISTER", "roles.quality_owner",
      "Set measurable quality objectives with owners, resources, deadlines, monitoring and evaluation methods.",
      []string{
        "Objectives are consistent with the quality policy and relevant to conformity of products/services and enhancement of customer satisfaction.",
        "Each objective identifies what will be done, required resources, responsible owner, completion date and how results will be evaluated.",
        "Objectives are communicated, monitored and updated when risks, customer needs, performance or business priorities change.",
      },
      []string{"Quality objective/KPI review"},
      []string{"ISO 9001:2015 clause 6.2"},
      []string{"organisation-specific targets and reporting frequency"},
      []string{"On-time service delivery", "Customer satisfaction/complaint trend", "First-time-right or error/rework rate", "Corrective actions closed on time", "Supplier performance", "Training/competence completion"}),

    tmpl("quality-risks", "QMS-6.1", "Quality Risks and Opportunities Register", "register", "QMS Planning", "REGISTER", "roles.quality_owner",
      "Record material risks and opportunities that can affect intended QMS results, customer satisfaction and conformity of products/services.",
      []string{
        "Risks and opportunities are identified from context, stakeholder requirements, process performance, complaints, suppliers, change, audits and operational experience.",
        "Actions are proportionate to potential impact and are integrated into relevant QMS processes rather than managed as disconnected paperwork.",
        "The effectiveness of actions is reviewed using process and performance evidence.",
      },
      []string{"Quality risk/opportunity register", "Evidence of completed actions"},
      []string{"ISO 9001:2015 clause 6.1"},
      []string{"priority quality risks/opportunities", "risk/action review frequency"}, nil),

    tmpl("change-planning", "QMS-6.3", "QMS Change Planning and Approval Procedure", "procedure", "Change Management", "PROCEDURE", "roles.quality_owner",
      "Plan QMS changes so intended outcomes, responsibilities, resources and system integrity are maintained.",
      []string{
        "Material changes are assessed before implementation for purpose, consequences, resource needs, responsibilities, process interactions, customer impact and QMS integrity.",
        "Affected documented information, competence, monitoring, suppliers and customer communications are updated as needed.",
        "Unintended effects are recorded and corrected, and significant changes receive post-implementation review.",
      },
      []string{"Completed change assessment", "Post-change review where applicable"},
      []string{"ISO 9001:2015 clause 6.3"},
      []string{"changes requiring formal approval", "change approval authority"}, nil),

    tmpl("resources", "QMS-7.1", "Quality Resources and Infrastructure Plan", "plan", "QMS Support", "PLAN", "roles.quality_owner",
      "Ensure people, infrastructure, environment, monitoring resources and organisational knowledge needed for process performance are available and maintained.",
      []string{
        "Resource needs are reviewed against workload, competence, technology, facilities, supplier dependence and quality objectives.",
        "Infrastructure and work environment needed for consistent service delivery are maintained and material failures are addressed.",
        "Monitoring/measuring resources are suitable for their intended purpose and are controlled where confidence in measurement is required.",
      },
      []string{"Resource review evidence", "Relevant maintenance/monitoring-resource records"},
      []string{"ISO 9001:2015 clause 7.1"},
      []string{"critical infrastructure/resources", "resource constraints and planned actions"}, nil),

    tmpl("knowledge", "QMS-7.1.6", "Organisational Knowledge Register", "register", "QMS Support", "REGISTER", "roles.quality_owner",
      "Identify, maintain and make available knowledge needed to operate processes and achieve conforming products/services.",
      []string{
        "Critical knowledge includes procedures, technical or service expertise, lessons learned, customer requirements, regulatory knowledge and supplier or system know-how.",
        "Knowledge concentration and loss risks are identified and reduced using documentation, training, handover, cross-training or succession arrangements.",
        "New knowledge needs are considered when services, technology, markets, customer expectations or obligations change.",
      },
      []string{"Organisational knowledge register", "Handover/training/knowledge-sharing evidence"},
      []string{"ISO 9001:2015 clause 7.1.6"},
      []string{"critical knowledge areas and single-person dependencies"}, nil),

    tmpl("competence-matrix", "QMS-7.2", "Quality Competence and Training Matrix", "register", "People", "REGISTER", "roles.quality_owner",
      "Map competence requirements to roles and retain evidence of training, experience and effectiveness.",
      []string{
        "Roles affecting quality have defined competence expectations based on education, training, skills or experience.",
        "Gaps are addressed through training, mentoring, reassignment, recruitment or other suitable action and effectiveness is evaluated.",
        "Evidence of competence and completed development actions is retained.",
      },
      []string{"Competence matrix", "Training/qualification evidence"},
      []string{"ISO 9001:2015 clauses 7.2-7.3"},
      []string{"role-specific competence requirements"}, nil),

    tmpl("communications", "QMS-7.4", "QMS Communication Plan", "plan", "QMS Support", "PLAN", "roles.quality_owner",
      "Define important internal and external quality communications, timing, audience, owner and method.",
      []string{
        "Communications cover policy, objectives, customer requirements, service changes, complaints, process performance, supplier issues, audit findings and improvement actions as relevant.",
        "External communications are accurate, authorised and consistent with contractual or regulatory commitments.",
      },
      []string{"QMS communication plan", "Examples of quality/customer communications"},
      []string{"ISO 9001:2015 clause 7.4"},
      []string{"customer escalation contacts and communication channels"}, nil),

    confidential(tmpl("customer-requirements", "QMS-8.2", "Customer Communication and Requirements Review Procedure", "procedure", "Customer", "PROCEDURE", "roles.quality_owner",
      "Ensure customer and applicable requirements are understood, reviewed, agreed, changed in a controlled way and communicated to delivery teams.",
      []string{
        "Customer communications cover enquiries, service/product information, contracts/orders, changes, feedback/complaints and customer property where relevant.",
        "Before commitment, requirements are reviewed for clarity, capability, differences from previous understanding and applicable statutory/regulatory requirements.",
        "Where the customer does not provide documented requirements, the organisation confirms them before acceptance where practical.",
        "Requirement changes are recorded and affected people are informed promptly.",
      },
      []string{"Completed requirements/contract review", "Evidence of changed requirement communication"},
      []string{"ISO 9001:2015 clause 8.2"},
      []string{"who may approve customer commitments and exceptions"}, nil)),

    tmpl("design-development", "QMS-8.3", "Design and Development Procedure", "procedure", "Design and Development", "PROCEDURE", "roles.quality_owner",
      "Control design and development where the organisation creates or materially changes products/services.",
      []string{
        "Design work is planned with stages, responsibilities, resources, reviews, verification/validation activities and interfaces proportionate to complexity and risk.",
        "Inputs include functional/performance requirements, legal/regulatory requirements, relevant prior knowledge and potential consequences of failure.",
        "Outputs are suitable for subsequent processes, include acceptance criteria and identify essential characteristics where relevant.",
        "Reviews, verification, validation and changes are documented, and issues are resolved before release or appropriately accepted.",
      },
      []string{"Design plan/record", "Review/verification/validation evidence", "Design change record"},
      []string{"ISO 9001:2015 clause 8.3"},
      []string{"whether design/development applies", "design approval and validation method"}, nil),

    confidential(tmpl("supplier-quality", "QMS-8.4", "External Provider Approval and Performance Procedure", "procedure", "Suppliers", "PROCEDURE", "roles.quality_owner",
      "Control externally provided processes, products and services according to their effect on conformity and customer requirements.",
      []string{
        "External providers are selected, approved and monitored using criteria proportionate to service/product criticality and risk.",
        "The organisation defines what will be controlled internally and at the provider, considering the provider's capability and effectiveness of its controls.",
        "Purchase/service requirements clearly communicate applicable specifications, approvals, competence, interactions, monitoring and verification needs.",
        "Provider performance is reviewed and poor performance triggers action, escalation or reapproval decisions.",
      },
      []string{"Approved supplier list", "Supplier assessment", "Supplier performance review"},
      []string{"ISO 9001:2015 clause 8.4"},
      []string{"supplier approval criteria and review frequency"}, nil)),

    tmpl("service-control", "QMS-8.5", "Service Delivery and Operational Control Procedure", "procedure", "Operations", "PROCEDURE", "roles.quality_owner",
      "Deliver products/services under controlled conditions with suitable information, resources, people, monitoring and release controls.",
      []string{
        "Delivery teams use current information defining required characteristics, results and acceptance criteria.",
        "Suitable monitoring/measuring resources, competent people, infrastructure and process controls are available where needed.",
        "Human-error prevention, identification/traceability, preservation, customer/external-provider property and post-delivery requirements are addressed where applicable.",
        "Changes during delivery are reviewed and authorised, and records show who approved material changes.",
      },
      []string{"Operational/service delivery records", "Relevant quality checks"},
      []string{"ISO 9001:2015 clause 8.5"},
      []string{"key service-delivery controls and acceptance criteria"}, nil),

    tmpl("customer-property", "QMS-8.5.3", "Customer and External Provider Property Register", "register", "Operations", "REGISTER", "roles.quality_owner",
      "Identify, verify, protect and report loss/damage of property belonging to customers or external providers while under organisational control.",
      []string{
        "Relevant physical, intellectual, data or other property is identified when received or accessed and protected according to its nature and requirements.",
        "Loss, damage or unsuitability is recorded and communicated to the owner with retained evidence.",
      },
      []string{"Property register where applicable", "Loss/damage communication evidence"},
      []string{"ISO 9001:2015 clause 8.5.3"},
      []string{"types of customer/external-provider property handled"}, nil),

    tmpl("release", "QMS-8.6", "Product and Service Release Checklist", "checklist", "Operations", "TEMPLATE", "roles.quality_owner",
      "Confirm planned acceptance requirements are met before product/service release or record authorised exception.",
      []string{
        "Required checks, reviews, testing or acceptance activities are completed before release unless otherwise approved by authorised personnel and, where applicable, the customer.",
        "Release records identify evidence of conformity to acceptance criteria and the person authorising release.",
      },
      []string{"Completed release/acceptance checklist"},
      []string{"ISO 9001:2015 clause 8.6"},
      []string{"release criteria and authorised releasers"},
      []string{"Requirements reviewed", "Required checks completed", "Known deviations accepted by authorised person", "Customer approval obtained where required", "Release authorised and evidence retained"}),

    confidential(tmpl("nonconforming-output", "QMS-8.7", "Nonconforming Output Procedure and Register", "procedure", "Improvement", "PROCEDURE", "roles.quality_owner",
      "Identify and control outputs that do not meet requirements so unintended use or delivery is prevented.",
      []string{
        "Nonconforming outputs are identified and controlled according to their nature and potential effect on conformity.",
        "Available responses include correction, segregation/containment, return/suspension, informing the customer and obtaining authorised concession where appropriate.",
        "After correction, conformity is reverified where relevant and records show the issue, action, concessions and decision authority.",
      },
      []string{"Nonconforming output register", "Completed example with disposition/verification"},
      []string{"ISO 9001:2015 clause 8.7"},
      []string{"who may approve concessions or release after correction"}, nil)),

    tmpl("monitoring-analysis", "QMS-9.1", "Quality Monitoring, Measurement and Analysis Plan", "plan", "QMS Performance", "PLAN", "roles.quality_owner",
      "Define what quality performance is measured, how, when, by whom and how results are analysed and evaluated.",
      []string{
        "Monitoring covers process performance, product/service conformity, customer satisfaction, supplier performance, objectives, risks/actions and QMS effectiveness as relevant.",
        "Methods provide valid results and records are retained as evidence.",
        "Data is analysed for trends, recurring problems, effectiveness of actions, improvement opportunities and need for change.",
      },
      []string{"Monitoring/measurement plan", "Recent analysis/performance report"},
      []string{"ISO 9001:2015 clause 9.1"},
      []string{"KPIs, data sources, frequency and owners"}, nil),

    tmpl("customer-satisfaction", "QMS-9.1.2", "Customer Satisfaction and Feedback Procedure", "procedure", "Customer", "PROCEDURE", "roles.quality_owner",
      "Monitor customer perceptions using suitable methods and convert feedback into action and improvement.",
      []string{
        "Feedback sources may include surveys, reviews, complaints, compliments, retention/renewal, meetings, service metrics and other direct or indirect signals.",
        "Results are analysed for trends and material dissatisfaction is investigated and linked to corrective action when appropriate.",
        "Customer feedback and complaint trends are reviewed by management.",
      },
      []string{"Customer satisfaction results", "Feedback/complaint trend analysis"},
      []string{"ISO 9001:2015 clause 9.1.2"},
      []string{"feedback methods, frequency and escalation threshold"}, nil),

    confidential(tmpl("complaints", "QMS-COMP", "Customer Complaint Handling Procedure and Register", "procedure", "Customer", "PROCEDURE", "roles.quality_owner",
      "Give staff a simple workflow to acknowledge, investigate, resolve, communicate and learn from customer complaints.",
      []string{
        "Complaints are logged with date, customer, issue, owner, severity and target response/closure dates.",
        "Material complaints are investigated objectively, with evidence preserved and root cause considered when recurrence is possible.",
        "Customers receive appropriate acknowledgement and outcome communication, subject to legal/contractual constraints.",
        "Trends and overdue/high-impact complaints are escalated and feed corrective action and management review.",
      },
      []string{"Complaint register", "Completed complaint and resolution evidence"},
      []string{"Supports ISO 9001 customer focus, 9.1.2 and 10.2"},
      []string{"complaint acknowledgement/closure targets"}, nil)),

    tmpl("measurement-resources", "QMS-7.1.5", "Monitoring and Measuring Resources Register", "register", "QMS Support", "REGISTER", "roles.quality_owner",
      "Maintain confidence that monitoring and measuring resources are suitable, maintained and traceable where measurement traceability is required.",
      []string{
        "Resources used to verify conformity are identified with purpose, owner/location, required accuracy or suitability, status and maintenance/calibration/verification arrangements where relevant.",
        "Where traceability is required, calibration/verification follows appropriate standards or documented basis and equipment is identified and protected from invalid adjustment/damage.",
        "When a resource is found unfit, the organisation assesses whether previous measurement results remain valid and takes appropriate action.",
      },
      []string{"Equipment/resource register", "Calibration/verification evidence where applicable"},
      []string{"ISO 9001:2015 clause 7.1.5"},
      []string{"which monitoring/measuring resources require calibration or formal verification"}, nil),

    tmpl("qms-audit", "QMS-9.2", "QMS Internal Audit Checklist and Report", "audit document", "Assurance", "REPORT", "roles.quality_owner",
      "Provide an audit-ready structure for testing QMS conformity, process effectiveness and implementation using evidence.",
      []string{
        "Audit scope and criteria cover applicable QMS requirements, internal arrangements and selected processes/locations.",
        "The auditor records sampled evidence, conformity observations, nonconformities and improvement opportunities without auditing their own work where objectivity would be impaired.",
        "Results are communicated and corrective actions are tracked without undue delay.",
      },
      []string{"Completed QMS audit report", "Evidence samples and findings"},
      []string{"ISO 9001:2015 clause 9.2"},
      []string{"audit scope, auditor and date"},
      []string{"Context and scope", "Leadership/policy/objectives", "Process controls and documented information", "Customer requirements and satisfaction", "Suppliers/external providers", "Service/product delivery and release", "Monitoring/measurement", "Nonconformity/corrective action", "Improvement"}),

    confidential(tmpl("qms-management-review", "QMS-9.3", "QMS Management Review Agenda and Minutes", "record", "Governance", "RECORD", "roles.executive_owner",
      "Provide a ready agenda and decision record covering required QMS performance and improvement inputs.",
      []string{
        "Review previous actions, context/interested-party changes, customer satisfaction, objectives, process/product/service performance, nonconformities/corrective actions, monitoring results, audit results, external provider performance, resource adequacy, risk/opportunity action effectiveness and improvement opportunities.",
        "Record decisions/actions related to improvement opportunities, needed QMS changes and resource needs.",
      },
      []string{"Approved QMS management-review minutes", "Supporting performance evidence"},
      []string{"ISO 9001:2015 clause 9.3"},
      []string{"meeting date, attendees, decisions and actions"}, nil)),

    tmpl("root-cause", "QMS-10.2", "Root Cause and Corrective Action Form", "form", "Improvement", "TEMPLATE", "roles.quality_owner",
      "Give teams a consistent record for correction, cause analysis, action, verification and closure.",
      []string{
        "Describe the nonconformity and available objective evidence.",
        "Record immediate correction/containment, cause analysis and whether similar problems exist or could occur elsewhere.",
        "Select proportionate corrective actions, owners and due dates, then verify effectiveness before closure.",
        "Update risks/opportunities and the QMS where the issue shows a systemic change is needed.",
      },
      []string{"Completed corrective-action form"},
      []string{"ISO 9001:2015 clause 10.2"},
      []string{"significant-action closure authority"},
      []string{"Problem/evidence", "Immediate correction/containment", "Root cause", "Similar risk elsewhere", "Corrective actions/owners/dates", "Effectiveness check", "Closure approval"}),

    tmpl("improvement", "QMS-10.3", "Continual Improvement Register", "register", "Improvement", "REGISTER", "roles.quality_owner",
      "Capture and prioritise improvement opportunities from data, people, customers, audits, suppliers, risk and management review.",
      []string{
        "Improvement opportunities are recorded with source, expected benefit, priority, owner, target date and outcome.",
        "Completed improvements are evaluated for effectiveness and useful lessons are shared or standardised where appropriate.",
      },
      []string{"Improvement register", "Completed improvement evidence"},
      []string{"ISO 9001:2015 clause 10.3"},
      []string{"improvement prioritisation criteria"}, nil),
  }

  return makePack(
    "iso9001",
    "Comp Plus+ ISO 9001 Fast Start",
    "2026.08.07",
    "ISO 9001:2015 + Amendment 1:2024 (2026 edition under publication)",
    "Ready-made QMS policies, process records, customer and supplier controls, audit, management review and improvement templates. Versioned for migration when ISO 9001:2026 is formally published.",
    templates,
    false,
    nil,
  )
}
