package templates

func corePack() Pack {
  templates := []TemplateDefinition{
    tmpl("context", "CORE-01", "Organisation Context and Interested Parties", "governance document", "Governance", "GOVERNANCE", "roles.system_manager",
      "Maintain a practical view of internal and external issues, interested parties, relevant requirements and changes that could affect the management system.",
      []string{
        "{{organization.legal_name}} reviews business strategy, services, technology, people, suppliers, legal obligations, market conditions and material external events when determining management-system context.",
        "Relevant interested parties are identified with their material requirements, including customers, workers, regulators, suppliers, owners, partners and certification or assurance stakeholders.",
        "Climate change is explicitly considered for relevance to the organisation and to requirements raised by relevant interested parties; the conclusion and rationale are recorded and reviewed when circumstances change.",
        "Context changes are reviewed at management review and when a significant organisational, legal, technology, supplier or incident-related event occurs.",
      },
      []string{"Current context and interested-parties review", "Evidence supporting material legal, customer or stakeholder requirements"},
      []string{"ISO/IEC 27001 clauses 4.1-4.2", "ISO 9001 clauses 4.1-4.2 including Amd 1:2024", "ISO 14001 context and interested parties", "ISO/IEC 42001 context and interested parties", "UK GDPR accountability"},
      []string{"main internal and external issues", "relevant interested parties and their key requirements", "whether climate change is relevant and why"},
      []string{"Customers — service quality, confidentiality, lawful processing and contractual commitments", "Workers — clear roles, competence, safe and reliable systems", "Regulators — applicable legal and regulatory obligations", "Critical suppliers — contractual, resilience, security, privacy and service expectations"}),

    tmpl("scope", "CORE-02", "Integrated Management System Scope", "governance document", "Governance", "GOVERNANCE", "roles.system_manager",
      "Define the organisational boundaries, services, locations, technologies, dependencies and justified exclusions covered by the management system.",
      []string{
        "The scope covers the people, processes, information, technology and third parties used to deliver {{organization.services}} across {{organization.locations}}.",
        "Interfaces and dependencies with outsourced or shared services are considered when determining boundaries.",
        "Any exclusion is documented with a clear reason and is reviewed to ensure it does not undermine applicable requirements or claimed conformity.",
        "The scope is reviewed after significant business, location, service, technology or supplier change.",
      },
      []string{"Approved scope statement", "Current organisation/service/location information"},
      []string{"ISO/IEC 27001 clause 4.3", "ISO 9001 clause 4.3", "ISO 14001 clause 4.3", "ISO/IEC 42001 clause 4.3"},
      []string{"systems and data environments included", "material outsourced activities and dependencies", "any exclusions and their justification"}, nil),

    tmpl("roles", "CORE-03", "Roles, Responsibilities and Authorities Register", "register", "Governance", "REGISTER", "roles.executive_owner",
      "Assign accountable owners and deputies so every important compliance responsibility has clear authority and escalation.",
      []string{
        "Senior management remains accountable for management-system effectiveness and provides resources and direction.",
        "The management-system manager coordinates implementation, evidence, reviews, audits and improvement actions.",
        "Security, privacy, quality, environmental and AI responsibilities are assigned to named people when those areas apply.",
        "Conflicts of responsibility and segregation needs are considered for sensitive approvals and assurance activities.",
      },
      []string{"Approved role register", "Organisation chart or equivalent evidence of authority"},
      []string{"ISO management-system leadership and role requirements", "UK GDPR accountability"},
      []string{"deputy for each critical role", "escalation route to senior management"},
      []string{"Executive owner — {{roles.executive_owner}}", "Management-system manager — {{roles.system_manager}}", "Security owner — {{roles.security_owner}}", "Privacy owner — {{roles.privacy_owner}}", "Quality owner — {{roles.quality_owner}}", "Environmental owner — {{roles.environment_owner}}", "AI governance owner — {{roles.ai_owner}}"}),

    tmpl("document-control", "CORE-04", "Document and Record Control Procedure", "procedure", "Governance", "PROCEDURE", "roles.system_manager",
      "Ensure controlled documents are identifiable, approved, current, accessible to authorised users, protected, retained and disposed of appropriately.",
      []string{
        "Controlled documents have a title, owner, status, effective date and review date and are approved before issue.",
        "Changes create a new controlled version; obsolete versions remain traceable where retention is required and are prevented from accidental operational use.",
        "Access follows business need and information classification. Sensitive records are protected against unauthorised access, alteration, loss and inappropriate disclosure.",
        "External documents needed for operations or compliance are identified and kept current.",
        "Retention and disposal follow legal, contractual, business and privacy requirements.",
      },
      []string{"Example approved version-controlled document", "Document/record retention evidence"},
      []string{"ISO/IEC 27001 clause 7.5", "ISO 9001 clause 7.5", "ISO 14001 documented information", "ISO/IEC 42001 documented information", "UK GDPR accountability"},
      []string{"primary controlled-document storage location", "default retention rules and disposal authority"}, nil),

    tmpl("risk", "CORE-05", "Integrated Risk and Opportunity Management Procedure", "procedure", "Risk Management", "PROCEDURE", "roles.system_manager",
      "Provide one repeatable method for identifying, analysing, evaluating, treating, accepting, monitoring and reviewing risks and opportunities.",
      []string{
        "Risks are described with a cause, event and potential consequence and are assigned to an accountable owner.",
        "Likelihood and impact are assessed using a consistent 5-by-5 scale unless an approved specialist method is more appropriate.",
        "Treatment options include reduce, avoid, transfer/share or accept; opportunities are considered alongside threats where relevant.",
        "Treatment actions have owners and target dates. Residual risk is reassessed after treatment and accepted by the appropriate authority.",
        "Risk reviews occur at planned intervals and after material change, incidents, audit findings or new obligations.",
      },
      []string{"Current risk register or risk analysis", "Approved high/residual-risk decisions"},
      []string{"ISO/IEC 27001 clauses 6.1.1-6.1.3 and 8.2-8.3", "ISO 9001 clause 6.1", "ISO 14001 planning", "ISO/IEC 42001 risk management", "UK GDPR risk-based accountability"},
      []string{"risk acceptance threshold", "who may accept high residual risk"},
      []string{"Suggested scale — likelihood 1 Rare to 5 Almost certain; impact 1 Insignificant to 5 Severe", "Suggested treatment trigger — scores above the approved appetite require a documented treatment or explicit acceptance"}),

    tmpl("objectives", "CORE-06", "Objectives and KPI Register", "register", "Performance", "REGISTER", "roles.executive_owner",
      "Set measurable objectives with owners, targets, deadlines, monitoring methods and actions when performance is off track.",
      []string{
        "Objectives are aligned with policy commitments, material risks, legal/contractual requirements and business priorities.",
        "Each objective has a measurable target where practicable, an owner, resources, target date and evaluation method.",
        "Performance is reviewed at a frequency proportionate to the objective and escalated when targets are missed.",
      },
      []string{"Current objectives/KPI review record"},
      []string{"ISO management-system objective and performance requirements"},
      []string{"organisation-specific targets and owners"},
      []string{"Compliance actions overdue — target agreed by management", "Internal audit programme completion — target 100% by cycle end", "Critical corrective actions closed on time — target agreed by management", "Mandatory training completion — target agreed by management"}),

    tmpl("training", "CORE-07", "Competence, Awareness and Training Procedure", "procedure", "People", "PROCEDURE", "roles.system_manager",
      "Identify competence needs, provide appropriate training and awareness, evaluate effectiveness and retain evidence.",
      []string{
        "Roles that can affect compliance or management-system performance have documented competence expectations.",
        "New starters receive relevant induction and workers receive periodic refresher or role-specific training based on risk and change.",
        "Training effectiveness is evaluated using suitable methods such as tests, observation, incidents, work quality or manager review.",
        "Training and competence evidence is retained and gaps are assigned corrective actions.",
      },
      []string{"Training matrix/register", "Recent completion or competence records"},
      []string{"ISO management-system competence and awareness requirements", "UK GDPR staff awareness/accountability"},
      []string{"mandatory induction topics", "refresher frequency for high-risk roles"}, nil),

    tmpl("suppliers", "CORE-08", "Supplier Due Diligence and Monitoring Procedure", "procedure", "Third Parties", "PROCEDURE", "roles.system_manager",
      "Apply proportionate due diligence, contracting, monitoring and exit controls to suppliers and outsourced services.",
      []string{
        "Suppliers are risk-tiered according to service criticality, data access, system access, legal exposure, substitutability and operational dependency.",
        "Due diligence is completed before approval for critical or high-risk suppliers and material risks are addressed in contracts or treatment plans.",
        "Contracts define applicable service, security, privacy, confidentiality, resilience, notification, audit and exit requirements.",
        "Performance and risk are reviewed at planned intervals and after material incidents or changes.",
        "Exit arrangements include return/transfer of information, access removal and verified deletion where applicable.",
      },
      []string{"Critical supplier register", "One completed supplier assessment", "Relevant contractual clauses or agreement"},
      []string{"ISO supplier/external provider controls", "UK GDPR processor/accountability requirements"},
      []string{"supplier risk tiers and review frequencies"}, nil),

    tmpl("incidents", "CORE-09", "Incident Management and Escalation Plan", "plan", "Operations", "PLAN", "roles.system_manager",
      "Provide a clear, tested method to report, triage, contain, investigate, communicate, recover from and learn from incidents.",
      []string{
        "Workers and relevant third parties know how to report incidents quickly and what information to provide.",
        "Incidents are classified by severity using impact, urgency, affected services/data, legal duties and stakeholder risk.",
        "The response owner coordinates containment, evidence preservation, recovery, communications and required notifications.",
        "Material incidents receive a documented post-incident review, root-cause analysis where appropriate and tracked improvement actions.",
        "The plan and contact routes are tested periodically and after major change.",
      },
      []string{"Incident register", "Recent incident/exercise record", "Current emergency contacts"},
      []string{"ISO incident and improvement requirements", "UK GDPR personal-data breach accountability"},
      []string{"24/7 or out-of-hours reporting route where needed", "severity definitions and notification decision owners"}, nil),

    tmpl("corrective-action", "CORE-10", "Nonconformity and Corrective Action Procedure", "procedure", "Improvement", "PROCEDURE", "roles.system_manager",
      "Ensure problems are controlled, root causes are addressed, recurrence risk is considered and corrective actions are verified for effectiveness.",
      []string{
        "Nonconformities are recorded from audits, incidents, complaints, monitoring, supplier issues, control failures or other sources.",
        "Immediate correction or containment is completed when needed to control impact.",
        "Root cause and similar potential issues are considered before selecting corrective action.",
        "Actions have owners and due dates; effectiveness is verified before closure and relevant risks/documents are updated.",
      },
      []string{"Corrective-action register", "Completed example showing effectiveness review"},
      []string{"ISO management-system nonconformity and corrective-action requirements"},
      []string{"closure approval authority for significant actions"}, nil),

    confidential(tmpl("obligations", "CORE-11", "Legal, Regulatory and Contractual Obligations Register", "register", "Governance", "REGISTER", "roles.system_manager",
      "Maintain a current record of applicable legal, regulatory, contractual, licence, customer and standards obligations with ownership and evidence.",
      []string{
        "Applicable obligations are identified from authoritative sources and contracts and assigned to responsible owners.",
        "Changes are reviewed periodically and when services, jurisdictions, contracts or regulations change.",
        "For each material obligation, the organisation records what it requires, how it is met, supporting evidence and review status.",
      },
      []string{"Reviewed obligations register", "Evidence for high-priority obligations"},
      []string{"ISO compliance obligations", "UK GDPR accountability"},
      []string{"jurisdictions and sector-specific obligations"},
      []string{"UK GDPR and Data Protection Act/related UK data law — confirm applicability", "Material customer/security clauses — add contract reference", "Employment, health/safety, environmental, sector or licence obligations — add where applicable"})),

    tmpl("internal-audit", "CORE-12", "Integrated Internal Audit Programme and Report", "plan", "Assurance", "PLAN", "roles.system_manager",
      "Plan and record objective internal audits that test whether the management system conforms to planned arrangements and is effectively implemented.",
      []string{
        "The audit programme considers process importance, risk, changes, previous results, incidents and unresolved findings.",
        "Each audit defines scope, criteria, method, timing and an auditor with sufficient objectivity and competence.",
        "Findings are evidence-based, communicated to responsible management and tracked to correction/corrective action where required.",
        "Audit results and programme status are inputs to management review.",
      },
      []string{"Annual/cycle audit programme", "Completed audit report and findings"},
      []string{"ISO/IEC 27001 clause 9.2", "ISO 9001 clause 9.2", "ISO 14001 internal audit", "ISO/IEC 42001 internal audit"},
      []string{"audit cycle and planned audit dates", "independent auditor(s)"}, nil),

    confidential(tmpl("management-review", "CORE-13", "Integrated Management Review Agenda and Minutes", "record", "Governance", "RECORD", "roles.executive_owner",
      "Give senior management a ready-made agenda and record for evaluating suitability, adequacy, effectiveness, resources, changes and improvement decisions.",
      []string{
        "Review previous actions, context and stakeholder changes, performance against objectives, audit results, incidents/nonconformities, risk status, supplier issues, legal/contractual changes, resources and improvement opportunities.",
        "Record decisions, approved changes, resource needs and actions with owners and due dates.",
        "Retain approved minutes as evidence and track actions to completion.",
      },
      []string{"Approved management-review minutes", "Evidence supporting reviewed KPIs, risks and actions"},
      []string{"ISO/IEC 27001 clause 9.3", "ISO 9001 clause 9.3", "ISO 14001 management review", "ISO/IEC 42001 management review"},
      []string{"meeting date and attendees", "decisions and action owners"},
      []string{"Previous actions", "Changes in context/interested parties including climate relevance", "Objectives and KPIs", "Risks and opportunities", "Audit and assurance results", "Incidents/nonconformities/complaints", "Supplier and resource performance", "Legal/contractual changes", "Improvement and resource decisions"})),
  }

  return makePack(
    "core",
    "Comp Plus+ Core Compliance Pack",
    "2026.08.07",
    "Integrated management-system foundation",
    "Ready-made shared governance documents used once across security, quality, environment, AI governance and privacy.",
    templates,
    false,
    nil,
  )
}
