package templates

func ukGDPRPack() Pack {
  templates := []TemplateDefinition{
    tmpl("data-protection-policy", "GDPR-ACCOUNTABILITY", "Data Protection and Privacy Policy", "policy", "Privacy Governance", "POLICY", "roles.privacy_owner",
      "Set practical rules for lawful, fair, transparent and accountable processing of personal information under current UK data-protection law.",
      []string{
        "{{organization.legal_name}} processes personal information only for identified purposes and using an appropriate lawful basis, with additional conditions where special-category or criminal-offence information is involved.",
        "Personal information is adequate, relevant and limited to what is needed, kept accurate, retained no longer than justified and protected using appropriate organisational and technical measures.",
        "People receive clear privacy information and can exercise applicable information rights through accessible request channels.",
        "High-risk processing is assessed before implementation, processors and sharing arrangements are controlled, and international transfers use an appropriate mechanism and safeguards.",
        "Breaches, complaints and nonconformities are recorded, investigated and used to improve controls and accountability.",
      },
      []string{"Approved data-protection policy", "Evidence policy was communicated"},
      []string{"UK GDPR accountability and data-protection principles", "Data (Use and Access) Act 2025 changes in force by 19 June 2026"},
      []string{"privacy owner/DPO status where applicable", "main privacy contact channel"}, nil),

    confidential(tmpl("data-map", "GDPR-DATAMAP", "Personal Data Flow Map and Inventory", "register", "Privacy Records", "REGISTER", "roles.privacy_owner",
      "Create a practical inventory showing what personal information exists, where it comes from, where it goes, who uses it and which systems/suppliers are involved.",
      []string{
        "Map personal-information flows by business activity rather than only by system so purposes, sources, recipients and responsibilities remain understandable.",
        "Record systems/storage, internal teams, processors/third parties, transfer locations and key security/retention controls for each material flow.",
        "Review the map when services, systems, suppliers, purposes or data categories change and reconcile changes with the ROPA and privacy notices.",
      },
      []string{"Current personal-data map/inventory", "Evidence of periodic review"},
      []string{"ICO accountability guidance on data mapping and records"},
      []string{"main data sources, systems, recipients and international locations"}, nil)),

    confidential(tmpl("ropa", "GDPR-ARTICLE30", "Record of Processing Activities (ROPA)", "register", "Privacy Records", "REGISTER", "roles.privacy_owner",
      "Maintain a current record of processing activities based on the organisation's actual personal-data flows.",
      []string{
        "For controller activities, record organisation/privacy contacts, purpose, categories of people and personal information, recipients, international transfers/safeguards, retention and a meaningful summary of security measures.",
        "Where acting as a processor, record relevant controller contacts, categories of processing, transfers/safeguards and security measures as applicable.",
        "Link processing activities to lawful-basis decisions, DPIAs, privacy notices, processors/contracts and retention rules so related records can be maintained consistently.",
        "Update the ROPA when processing changes and periodically verify it against actual practice with relevant teams.",
      },
      []string{"Current ROPA", "Review/owner evidence"},
      []string{"UK GDPR Article 30", "ICO documentation and accountability guidance"},
      []string{"processing activities by department/service"},
      []string{"Activity name", "Controller/processor role", "Purpose", "Categories of people", "Personal-data categories", "Lawful basis/conditions", "Recipients/processors", "International transfers/safeguards", "Retention", "Security measures", "Owner/review date"})),

    confidential(tmpl("lawful-basis", "GDPR-LAWFUL-BASIS", "Lawful Basis and Special Category Conditions Register", "register", "Privacy Governance", "REGISTER", "roles.privacy_owner",
      "Record why each processing purpose is lawful and document any additional condition required for special-category or criminal-offence information.",
      []string{
        "Select the lawful basis before processing begins and assess it against the real purpose and relationship rather than choosing a convenient label retrospectively.",
        "Where special-category information is processed, record both the Article 6 basis and an appropriate Article 9 condition plus any additional UK-law requirement that applies.",
        "Where criminal-offence information is processed, record the applicable condition and safeguards.",
        "Reassess the decision if the purpose, context, data, relationship or law changes and align privacy notices and the ROPA.",
      },
      []string{"Lawful-basis register", "Supporting assessments/records"},
      []string{"UK GDPR lawful-basis and accountability requirements"},
      []string{"lawful basis for each material purpose", "special-category/criminal-offence conditions where relevant"}, nil)),

    confidential(tmpl("lia", "GDPR-LIA", "Legitimate Interests Assessment (LIA)", "assessment", "Privacy Assessment", "TEMPLATE", "roles.privacy_owner",
      "Provide a consistent assessment before relying on legitimate interests for material processing.",
      []string{
        "Purpose test: identify the legitimate interest and whether the processing genuinely helps achieve it.",
        "Necessity test: consider whether the purpose can reasonably be achieved using a less intrusive method.",
        "Balancing test: assess reasonable expectations, nature of information, relationship, likely impact, safeguards and any vulnerability or power imbalance.",
        "Document the conclusion, safeguards and review triggers and ensure transparency reflects the legitimate interest relied upon.",
      },
      []string{"Completed LIA", "Evidence safeguards were implemented"},
      []string{"UK GDPR legitimate-interests accountability"},
      []string{"purpose/interest", "necessity", "balancing factors", "final decision and safeguards"}, nil)),

    tmpl("privacy-notice", "GDPR-TRANSPARENCY", "Customer and Service User Privacy Notice", "notice", "Transparency", "TEMPLATE", "roles.privacy_owner",
      "Give customers/service users clear, layered information about how their personal information is used.",
      []string{
        "Identify {{organization.legal_name}}, privacy contact details and the main purposes/lawful bases for processing.",
        "Explain categories/sources where information is not obtained directly, material recipients/processors, international transfers and safeguards, retention approach and applicable rights.",
        "Explain the right to complain to the organisation and to the ICO, and provide clear channels for rights requests and privacy complaints.",
        "Where relevant, explain significant automated decision-making/profiling and meaningful information about safeguards and human involvement.",
      },
      []string{"Published customer privacy notice", "Change/review record"},
      []string{"UK GDPR transparency requirements", "DUAA 2025 changes in force in 2026"},
      []string{"actual purposes/lawful bases", "recipients/transfers", "retention summaries", "rights/privacy contact details"}, nil),

    confidential(tmpl("employee-privacy", "GDPR-EMPLOYEE-NOTICE", "Worker and Applicant Privacy Notice", "notice", "Transparency", "TEMPLATE", "roles.privacy_owner",
      "Provide workers and applicants with clear information about HR, recruitment, payroll, performance, security and related personal-data processing.",
      []string{
        "Describe recruitment and employment purposes, lawful bases/conditions, key data sources and categories, internal/external recipients and retention approach.",
        "Explain monitoring or security-related processing where applicable with proportionate transparency and safeguards.",
        "Explain rights, complaint routes, international transfer arrangements and privacy contacts.",
      },
      []string{"Published worker/applicant privacy notice"},
      []string{"UK GDPR transparency and employment-data accountability"},
      []string{"actual HR/recruitment systems and processors", "monitoring activities if any", "retention periods"}, nil)),

    confidential(tmpl("retention", "GDPR-RETENTION", "Personal Data Retention and Disposal Schedule", "register", "Records Management", "REGISTER", "roles.privacy_owner",
      "Define justified retention periods, triggers, disposal methods and owners for categories of personal information and business records.",
      []string{
        "Retention is based on legal/regulatory, contractual, evidential and genuine business need rather than indefinite default storage.",
        "Each record category identifies a retention trigger, period or review rule, owner and secure disposal/anonymisation method.",
        "Legal hold, dispute or investigation needs can suspend normal disposal through a documented exception.",
        "Automated and manual deletion processes are periodically checked for effectiveness, including relevant processor/cloud locations where possible.",
      },
      []string{"Retention schedule", "Deletion/disposal evidence or review"},
      []string{"UK GDPR storage limitation and accountability", "ICO records-management guidance"},
      []string{"record categories, legal/business basis and actual retention periods"}, nil)),

    tmpl("dpia-screening", "GDPR-DPIA-SCREEN", "DPIA Screening Checklist", "checklist", "Privacy Assessment", "TEMPLATE", "roles.privacy_owner",
      "Help teams decide early whether proposed processing is likely to result in high risk and requires a full DPIA.",
      []string{
        "Screen new or materially changed processing before implementation using nature, scope, context, purpose, technology, scale and potential impact on people.",
        "Flag systematic monitoring, large-scale sensitive data, significant automated decisions, vulnerable people, new technology, matching datasets, denial of service/rights or other high-risk characteristics for privacy review.",
        "Record the screening decision and rationale even when a full DPIA is not required.",
      },
      []string{"Completed DPIA screening"},
      []string{"UK GDPR DPIA requirements", "ICO DPIA guidance"},
      []string{"project/processing description and screening conclusion"}, nil),

    confidential(tmpl("dpia", "GDPR-DPIA", "Data Protection Impact Assessment (DPIA)", "assessment", "Privacy Assessment", "TEMPLATE", "roles.privacy_owner",
      "Assess necessity, proportionality, privacy risks and safeguards before high-risk processing begins.",
      []string{
        "Describe processing operations, purposes, data flows, technology, parties, scale, context and intended outcomes.",
        "Assess necessity and proportionality including lawful basis, transparency, minimisation, accuracy, retention, rights, processors/transfers and security.",
        "Identify risks to people's rights and freedoms, assess likelihood/severity and record measures to eliminate or reduce those risks.",
        "Seek appropriate stakeholder/data-protection advice and record consultation where relevant; unresolved high residual risk is escalated for required regulatory consultation before processing.",
        "Review the DPIA when risk, purpose, technology or processing changes materially.",
      },
      []string{"Approved DPIA", "Evidence safeguards/actions were completed"},
      []string{"UK GDPR Articles 35-36", "ICO DPIA guidance"},
      []string{"processing description", "necessity/proportionality", "risk ratings", "mitigations", "residual-risk approval/consultation"}, nil)),

    tmpl("rights-procedure", "GDPR-RIGHTS", "Information Rights and Subject Access Request Procedure", "procedure", "Information Rights", "PROCEDURE", "roles.privacy_owner",
      "Give staff a reliable workflow for recognising, validating, searching, reviewing and responding to information-rights requests within applicable legal time limits.",
      []string{
        "Requests are recognised regardless of channel or wording and routed promptly to the privacy owner without unnecessary formality.",
        "Identity is verified only to the extent reasonable and proportionate to the risk of unauthorised disclosure.",
        "Searches are reasonable and proportionate, using relevant systems, teams and processors, and records show searches and decisions made.",
        "Potential exemptions, third-party information, privilege/confidentiality and manifestly unfounded/excessive issues receive appropriate review before disclosure or refusal.",
        "Responses use a secure channel and explain relevant decisions, rights to complain and further recourse where required.",
      },
      []string{"Rights/SAR procedure", "Completed rights-request record"},
      []string{"UK GDPR information rights", "ICO subject access guidance updated July 2026"},
      []string{"central request channel", "request owner/deputy", "systems/search owners"}, nil),

    confidential(tmpl("rights-register", "GDPR-RIGHTS-REGISTER", "Information Rights Request Register", "register", "Information Rights", "REGISTER", "roles.privacy_owner",
      "Track rights requests from receipt through identity/search/review/response and retain evidence of timeliness and decisions.",
      []string{
        "Record request type, received date, requester/contact, identity status, scope/clarification, deadline, search owners, decision, response date and outcome.",
        "Record pauses/extensions or refusal/exemption decisions only where legally justified and keep enough information to explain the handling without retaining unnecessary copies of disclosed data.",
      },
      []string{"Current rights-request register", "Response evidence"},
      []string{"UK GDPR information-rights accountability"},
      []string{"current/open requests"}, nil)),

    tmpl("sar-response-pack", "GDPR-SAR-TEMPLATES", "Subject Access Response Letter Pack", "form", "Information Rights", "TEMPLATE", "roles.privacy_owner",
      "Provide editable acknowledgement, clarification/identity request and final-response wording so teams respond consistently while still tailoring each case.",
      []string{
        "Acknowledgement confirms receipt, contact point and next steps without prejudging entitlement or scope.",
        "Any identity/clarification request explains why the information is reasonably needed and avoids collecting more identity data than necessary.",
        "The final response explains the outcome, provides required supplementary information and explains complaint/escalation options where applicable.",
      },
      []string{"Completed case correspondence"},
      []string{"ICO subject access guidance updated July 2026"},
      []string{"privacy contact details and approved secure-delivery method"},
      []string{"Acknowledgement template", "Proportionate identity/clarification request template", "Full/partial response cover letter", "Refusal/limitation response structure for legal review"}),

    confidential(tmpl("breach-procedure", "GDPR-BREACH", "Personal Data Breach Response and Notification Procedure", "procedure", "Breach Management", "PROCEDURE", "roles.privacy_owner",
      "Detect, contain, assess, document and where required notify personal-data breaches promptly while coordinating security and operational response.",
      []string{
        "Suspected personal-data breaches are reported immediately and logged even when external notification is ultimately not required.",
        "Assess what happened, affected data/people, likely consequences, scale, sensitivity, safeguards and likelihood/severity of risk to people.",
        "Where notification to the ICO is legally required, prepare and submit available information within the applicable timeframe and provide further information in phases where necessary.",
        "Where a high risk to people requires communication, use clear language explaining the breach, likely consequences, measures taken and practical protective steps.",
        "Document the facts, effects, decisions, rationale and remedial action for every material breach and feed lessons into controls and risk management.",
      },
      []string{"Breach procedure", "Completed breach assessment/register entry", "Notification/communication evidence where applicable"},
      []string{"UK GDPR Articles 33-34", "ICO breach-response/accountability guidance"},
      []string{"incident/privacy escalation contacts", "who approves regulatory/individual notification"}, nil)),

    confidential(tmpl("breach-register", "GDPR-BREACH-REGISTER", "Personal Data Breach Register and Risk Assessment", "register", "Breach Management", "REGISTER", "roles.privacy_owner",
      "Keep a consistent record of breach facts, risk assessment, notifications, actions and lessons learned.",
      []string{
        "Record discovery/date, incident reference, systems/processes, data categories, approximate people/records, security characteristics and immediate containment.",
        "Assess likely consequences and risk/high-risk status with evidence-based rationale.",
        "Record ICO and individual-notification decisions, dates/content, actions, owners, closure and lessons learned.",
      },
      []string{"Current breach register"},
      []string{"UK GDPR breach documentation requirements"},
      []string{"any current/open breach actions"}, nil)),

    tmpl("privacy-complaints", "GDPR-COMPLAINTS", "Data Protection Complaints Procedure and Register", "procedure", "Privacy Complaints", "PROCEDURE", "roles.privacy_owner",
      "Meet the 2026 UK requirement for an accessible data-protection complaints process and use complaints to identify improvement opportunities.",
      []string{
        "People are given a clear electronic and/or other accessible way to raise a complaint about use of their personal information.",
        "Complaints are acknowledged within 30 days and investigated appropriately; the organisation communicates the outcome without undue delay.",
        "Records identify the complaint, evidence considered, investigation, outcome, communications and resulting actions while protecting sensitive information.",
        "Responses explain how the person can escalate to the ICO where appropriate.",
        "Complaint trends and recurring root causes are reviewed and linked to corrective action, training or process improvement.",
      },
      []string{"Published complaints route/procedure", "Complaint register", "Completed complaint response where available"},
      []string{"Data (Use and Access) Act 2025 complaints duty in force 19 June 2026", "ICO data-protection complaints guidance"},
      []string{"complaint submission route", "complaint investigation owner/deputy"},
      []string{"Reference", "Date received", "Acknowledgement date", "Issue and scope", "Investigator", "Evidence/actions", "Outcome", "Response date", "Corrective/improvement actions"}),

    confidential(tmpl("processor-due-diligence", "GDPR-PROCESSORS", "Processor Due Diligence and Contract Checklist", "checklist", "Third Parties", "TEMPLATE", "roles.privacy_owner",
      "Assess processors before appointment and verify contracts contain appropriate data-protection terms and operational safeguards.",
      []string{
        "Assess processor capability, security, confidentiality, locations/transfers, sub-processing, incident response, rights support, retention/deletion and assurance proportionate to risk.",
        "Document controller instructions, processing subject/duration/nature/purpose, data/people categories and required processor obligations in the contract or equivalent legally binding terms.",
        "Changes to sub-processors, locations or material service arrangements trigger review where relevant.",
        "At exit, confirm return/deletion and access removal subject to lawful retention requirements.",
      },
      []string{"Completed processor assessment", "Data-processing terms/agreement", "Exit/deletion evidence where applicable"},
      []string{"UK GDPR controller-processor requirements", "ICO accountability/contracts guidance"},
      []string{"critical processors and approved sub-processor/location conditions"}, nil)),

    confidential(tmpl("data-sharing", "GDPR-SHARING", "Data Sharing Assessment and Agreement Checklist", "assessment", "Data Sharing", "TEMPLATE", "roles.privacy_owner",
      "Assess whether sharing personal information is lawful, necessary, proportionate, secure and transparent before material recurring or high-risk sharing.",
      []string{
        "Identify parties/roles, purpose, data/people, lawful basis/conditions, necessity, expectations, risks and whether the sharing changes the original purpose.",
        "Define minimisation, accuracy, secure transfer, retention/deletion, rights handling, incident cooperation and review responsibilities.",
        "Use an appropriate data-sharing agreement or contract where it helps demonstrate and operate clear responsibilities.",
        "Update privacy information and ROPA where the sharing is material and not already accurately reflected.",
      },
      []string{"Completed sharing assessment", "Agreement/contract where appropriate"},
      []string{"UK GDPR accountability and ICO data-sharing guidance"},
      []string{"sharing purpose, parties, legal basis and safeguards"}, nil)),

    confidential(tmpl("international-transfer", "GDPR-TRANSFERS", "International Transfer Assessment Register", "assessment", "International Transfers", "REGISTER", "roles.privacy_owner",
      "Record international transfers, applicable transfer mechanism and risk/safeguard assessment where required.",
      []string{
        "Identify exporter/importer roles, destination, data categories, purpose, frequency, systems/processors and onward-transfer arrangements.",
        "Record the lawful transfer mechanism or adequacy basis and any required risk assessment or supplementary safeguards.",
        "Review transfers when destination law, importer, services, data, mechanism or regulatory guidance changes materially.",
      },
      []string{"Transfer register", "Transfer mechanism/assessment evidence"},
      []string{"UK GDPR international transfer requirements"},
      []string{"international destinations, transfer mechanisms and supplementary safeguards"}, nil)),

    tmpl("consent", "GDPR-CONSENT", "Consent and Preference Register", "register", "Privacy Governance", "REGISTER", "roles.privacy_owner",
      "Record and manage consent only where it is the appropriate lawful basis, including evidence, preferences and withdrawal.",
      []string{
        "Consent requests are specific, informed, freely given and expressed through a clear affirmative action, and are separate from unnecessary conditions of service.",
        "Evidence records who consented, when, what they were told and how they indicated consent.",
        "Withdrawal is as easy as giving consent and changes are propagated to relevant systems/processors without undue delay.",
        "Consent is refreshed or reassessed when purpose, processing or expectations change materially.",
      },
      []string{"Consent/preference register", "Example consent wording and withdrawal route"},
      []string{"UK GDPR consent requirements", "PECR where electronic marketing/cookies apply"},
      []string{"processing activities relying on consent"}, nil),

    tmpl("cookies", "GDPR-COOKIES", "Cookie and Tracking Technology Register", "register", "Privacy and PECR", "REGISTER", "roles.privacy_owner",
      "Inventory website/app tracking technologies, purposes, providers, lifetimes and consent/configuration status.",
      []string{
        "Record each cookie/tracker or material category, provider, purpose, data access, duration, first/third-party status and whether consent is required under applicable rules.",
        "Non-essential technologies are not activated before required consent and preference changes are respected.",
        "Public cookie/privacy information matches actual deployed technologies and the register is reviewed after website/app or supplier change.",
      },
      []string{"Cookie/tracker inventory", "Consent/banner configuration evidence"},
      []string{"PECR and UK data-protection transparency/accountability"},
      []string{"current website/app trackers and providers"}, nil),

    confidential(tmpl("children-vulnerable", "GDPR-VULNERABLE", "Children and Vulnerable Individuals Privacy Assessment", "assessment", "Privacy Assessment", "TEMPLATE", "roles.privacy_owner",
      "Assess additional risks and safeguards when processing can materially affect children or other people who may be vulnerable in the relevant context.",
      []string{
        "Consider age, capacity, reasonable expectations, power imbalance, sensitivity, targeting/profiling, transparency needs and potential for distress, exclusion or other harm.",
        "Use age/ability-appropriate transparency and interfaces where relevant and minimise collection, sharing, retention and behavioural influence.",
        "Record any consent/parental-authority or other legal requirements applicable to the specific service and processing.",
      },
      []string{"Completed vulnerability/children assessment"},
      []string{"UK GDPR fairness, transparency, risk and children's-data requirements"},
      []string{"whether children/vulnerable groups are in scope and additional safeguards"}, nil)),

    confidential(tmpl("privacy-by-design", "GDPR-DESIGN", "Data Protection by Design and Default Checklist", "checklist", "Privacy Assessment", "TEMPLATE", "roles.privacy_owner",
      "Embed privacy requirements into projects, systems and process changes before personal information is collected or materially changed.",
      []string{
        "Define purpose, lawful basis, minimum data, access, retention, transparency, rights, processor/sharing and security requirements during planning.",
        "Default settings collect/use/share only what is needed for the stated purpose unless the person chooses otherwise where appropriate.",
        "Complete DPIA screening and supplier/transfer checks early enough for findings to influence design.",
        "Record privacy decisions, exceptions and approvals and verify required safeguards before launch.",
      },
      []string{"Completed privacy-by-design checklist", "Launch/change approval evidence"},
      []string{"UK GDPR data protection by design/default", "ICO guidance updated for DUAA in February 2026"},
      []string{"project/system and privacy decisions"}, nil)),

    confidential(tmpl("automated-decisions", "GDPR-AUTOMATION", "Automated Decision-Making and Profiling Assessment", "assessment", "Privacy Assessment", "TEMPLATE", "roles.privacy_owner",
      "Assess legal basis, significance, fairness, transparency and safeguards for automated decision-making or profiling involving personal information.",
      []string{
        "Determine whether the activity is solely automated and whether it produces legal or similarly significant effects, and identify the information and logic/factors used at an understandable level.",
        "Record the lawful basis and any restrictions for special-category information, and assess necessity, fairness, discrimination/bias, accuracy and reasonable expectations.",
        "Where required, provide meaningful human intervention, ability to express a view/challenge a decision and appropriate transparency.",
        "Monitor outcomes and complaints and reassess after material model/data/purpose changes.",
      },
      []string{"Automated-decision/profiling assessment", "Human-review/challenge and monitoring evidence"},
      []string{"UK GDPR automated decision-making/profiling rules as amended by DUAA 2025"},
      []string{"systems/decisions in scope, legal basis and safeguards"}, nil)),

    tmpl("privacy-training", "GDPR-TRAINING", "Privacy Awareness and Role-Based Training Plan", "plan", "People", "PLAN", "roles.privacy_owner",
      "Provide proportionate privacy training and evidence for staff who handle personal information, rights requests, complaints, breaches or high-risk processing.",
      []string{
        "All relevant workers receive induction and refresher training covering data-protection principles, secure handling, rights, complaints, breach reporting and internal escalation.",
        "Specialist roles receive additional training appropriate to their decisions and responsibilities.",
        "Completion and effectiveness are monitored and recurring errors/incidents influence future training priorities.",
      },
      []string{"Privacy training plan", "Completion/effectiveness evidence"},
      []string{"UK GDPR accountability and ICO training expectations"},
      []string{"training frequency and specialist roles"}, nil),
  }

  return makePack(
    "uk-gdpr",
    "Comp Plus+ UK GDPR Fast Start",
    "2026.08.07",
    "Current UK GDPR, Data Protection Act framework and Data (Use and Access) Act 2025 changes in force in 2026",
    "Ready-made privacy governance, ROPA, lawful-basis, DPIA, rights, complaints, breach, processor, sharing, transfer, retention and transparency templates aligned to current ICO guidance.",
    templates,
    false,
    nil,
  )
}
