name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/extras=s3-cache"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "runs-on/action@4e5f72399b6b17f2e79c511c1b38a315a64d22dc" # v2
      - uses: "trufflesecurity/trufflehog@6f3c981e7b77f235fd2702dd74af25fc4b72bf11" # main
        with:
          extra_args: "--results=verified,unknown --exclude-paths=.trufflehog-exclude"
